### ISSUE TITLE
Error when mixing f32 and f64 in a model

### ISSUE THREAD

**Issue by Co1lin** [iree-org/iree#10348]
### What happened?

Update: See the comments below.

Compiler

### Version information

iree-compiler                20220909.261
iree-runtime                 20220909.261
iree-tools-tf                20220909.261

tensorflow                   2.9.1
tensorflow-addons            0.17.1
tensorflow-estimator         2.9.0
tensorflow-io-gcs-filesystem 0.26.0

**Comment by Co1lin** [comment]
A more simple example to reproduce this bug:

```python
from __future__ import annotations

import os
import pickle
from os import PathLike
from typing import Any, Callable, Dict, List, Tuple, Type

import numpy as np
import tensorflow as tf  # type: ignore
from tensorflow import keras
from keras import layers
import iree.compiler.tf
import iree.runtime
from multipledispatch import dispatch  # type: ignore

from icecream import ic

def configure_tensorflow():
    # https://github.com/tensorflow/tensorflow/issues/57359
    # tf.config.experimental.enable_tensor_float_32_execution(False)
    for gpu in tf.config.experimental.list_physical_devices("GPU"):
        tf.config.experimental.set_memory_growth(gpu, True)


configure_tensorflow()

class MyModule(tf.Module):
    def __init__(self) -> None:
        super().__init__()
        self.const = tf.constant(1.0, dtype=tf.float64)
    
    @tf.function
    def call(self, x_0):
        x_0_f64 = tf.cast(x_0, tf.float64)
        x_0_f64 = tf.math.add(x_0_f64, self.const)
        return {"output": x_0_f64}

if __name__ == '__main__':
    model = MyModule()

    x_0 = tf.random.normal([1, 64, 64, 3])

    ic(model.call(x_0))

    model_save_path = os.path.join('saved_model')
    tf.saved_model.save(model, model_save_path)

    loaded_model = tf.saved_model.load(model_save_path)

    ic(loaded_model.call(x_0))

    backend_choice = 'llvm-cpu'
    vm_flatbuffer = iree.compiler.tf.compile_module(
        model,
        target_backends=[backend_choice],
        exported_names=['call'],
        extra_args=["--iree-mhlo-demote-i64-to-i32=false",
                    "--iree-flow-demote-i64-to-i32"]
    ) # error occurs here

    compiled_model = iree.runtime.load_vm_flatbuffer(
        vm_flatbuffer,
        backend=backend_choice
    )
    
    ic(compiled_model.call(x_0))
```

**Comment by Co1lin** [comment]
Hi! is there anyone looking into this? Thanks. @benvanik

**Comment by jpienaar** [comment]
Can you try not demoting both? (Seems like one i64 to i32 conversion is enabled and one disabled, try testing with both enabled or both disabled; these demotions are partial today and seems like one is being too aggressive).

**Comment by Co1lin** [comment]
@jpienaar Hi, thanks for your reply! I tried to remove `extra_args` or set both of the options above to true or false, but in all cases I still got this error. I also tried to minimize this issue, and found that with only the add operator, if I still wanted to add the `self.const`, the compilation would fail if use float64. If I only used `x_0 = tf.math.add(x_0, x_0)`, the compilation succeeded but the running failed. See the codes below.

Failed when compiling:

```python
from __future__ import annotations

import os
import iree.compiler.tf
import iree.runtime
import tensorflow as tf  # type: ignore

from icecream import ic

def configure_tensorflow():
    # https://github.com/tensorflow/tensorflow/issues/57359
    # tf.config.experimental.enable_tensor_float_32_execution(False)
    for gpu in tf.config.experimental.list_physical_devices("GPU"):
        tf.config.experimental.set_memory_growth(gpu, True)


configure_tensorflow()

class MyModule(tf.Module):
    def __init__(self) -> None:
        super().__init__()
        self.const = tf.constant(1.0, shape=[1,64,64,3], dtype=tf.float64)
    
    @tf.function
    def call(self, x_0):
        x_0 = tf.math.add(x_0, self.const)
        return {"output": x_0}

if __name__ == '__main__':
    model = MyModule()

    x_0 = tf.random.normal([1, 64, 64, 3], dtype=tf.float64)

    ic(model.call(x_0))

    model_save_path = os.path.join('saved_model')
    tf.saved_model.save(model, model_save_path)

    loaded_model = tf.saved_model.load(model_save_path)

    ic(loaded_model.call(x_0))

    backend_choice = 'llvm-cpu'
    vm_flatbuffer = iree.compiler.tf.compile_module(
        model,
        target_backends=[backend_choice],
        exported_names=['call'],
    ) # error occurs here

    compiled_model = iree.runtime.load_vm_flatbuffer(
        vm_flatbuffer,
        backend=backend_choice
    )
    
    ic(compiled_model.call(x_0))
```

```python
Traceback (most recent call last):
  File "/home/colin/code/nnsmith/bugiree.py", line 44, in <module>
    vm_flatbuffer = iree.compiler.tf.compile_module(
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/iree/compiler/tools/tf.py", line 233, in compile_module
    return do_it(td)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/iree/compiler/tools/tf.py", line 227, in do_it
    return compile_saved_model(saved_model_dir, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/iree/compiler/tools/tf.py", line 204, in compile_saved_model
    result = invoke_pipeline([import_cl, compile_cl])
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/iree/compiler/tools/binaries.py", line 259, in invoke_pipeline
    raise CompilerToolError(stage.completed)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile
Diagnostics:
<unknown>:0: error: 'ml_program.global_load' op cannot load from global typed 'tensor<1x64x64x3xf64>' as 'tensor<1x64x64x3xf32>'
compilation failed


Invoked with:
 iree-compile /home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/iree/compiler/tools/../_mlir_libs/iree-compile - --iree-input-type=xla --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=llvm-cpu --iree-llvm-embedded-linker-path=/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false

Need more information? Set IREE_SAVE_TEMPS=/some/dir in your environment to save all artifacts and reproducers.
```

Failed when running:

```python
from __future__ import annotations

import os
import iree.compiler.tf
import iree.runtime
import tensorflow as tf  # type: ignore

from icecream import ic

def configure_tensorflow():
    # https://github.com/tensorflow/tensorflow/issues/57359
    # tf.config.experimental.enable_tensor_float_32_execution(False)
    for gpu in tf.config.experimental.list_physical_devices("GPU"):
        tf.config.experimental.set_memory_growth(gpu, True)


configure_tensorflow()

class MyModule(tf.Module):
    def __init__(self) -> None:
        super().__init__()
        # self.const = tf.constant(1.0, shape=[1,64,64,3], dtype=tf.float64)
    
    @tf.function
    def call(self, x_0):
        x_0 = tf.math.add(x_0, x_0)
        return {"output": x_0}

if __name__ == '__main__':
    model = MyModule()

    x_0 = tf.random.normal([1, 64, 64, 3], dtype=tf.float64)

    ic(model.call(x_0))

    model_save_path = os.path.join('saved_model')
    tf.saved_model.save(model, model_save_path)

    loaded_model = tf.saved_model.load(model_save_path)

    ic(loaded_model.call(x_0))

    backend_choice = 'llvm-cpu'
    vm_flatbuffer = iree.compiler.tf.compile_module(
        model,
        target_backends=[backend_choice],
        exported_names=['call'],
    ) # error occurs here

    compiled_model = iree.runtime.load_vm_flatbuffer(
        vm_flatbuffer,
        backend=backend_choice
    )
    
    ic(compiled_model.call(x_0))

```

```python
Traceback (most recent call last):
  File "/home/colin/code/nnsmith/bugiree.py", line 55, in <module>
    ic(compiled_model.call(x_0))
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/iree/runtime/function.py", line 130, in __call__
    self._invoke(arg_list, ret_list)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/iree/runtime/function.py", line 154, in _invoke
    self._vm_context.invoke(self._vm_function, arg_list, ret_list)
ValueError: Error invoking function: main_checkout/runtime/src/iree/modules/hal/utils/buffer_diagnostics.c:182: INVALID_ARGUMENT; tensor element type mismatch; expected f32 (21000020) but have f64 (21000040); while invoking native function hal.buffer_view.assert; while calling import; 
[ 1]   native hal.buffer_view.assert:0 -
[ 0] bytecode module.call:240 [unknown]
```

**Comment by Co1lin** [comment]
`float32` works fine, so I think there's some issue with `float64` in IREE.

**Comment by jpienaar** [comment]
Could you set IREE_SAVE_TEMPS=/some/dir and upload the reproducer? It'll greatly simplify repro.

And yes F64 is partial (across many of the backends/compilers I work with, so not too surprising).

**Comment by Co1lin** [comment]
Thanks for your reply! I ran the code with compilation failure, and got this.

[iree_save.zip](https://github.com/iree-org/iree/files/9709446/iree_save.zip)
