### ISSUE TITLE
`latest-snapshot` branch failed to update properly at the end of candidate release

### ISSUE THREAD

**Issue by hcindyl** [iree-org/iree#10590]
### What happened?

`Validate and Publish Release` has been failing for the last 9 days
https://github.com/iree-org/iree/actions/workflows/validate_and_publish_release.yml

This caused the latest candidate out of sync with the `latest-snapshot` branch.

The log shows
```
Push to branch latest-snapshot
remote: error: GH006: Protected branch update failed for refs/heads/latest-snapshot.        
remote: error: Cannot force-push to this protected branch        
To https://github.com/iree-org/iree.git
 ! [remote rejected]     HEAD -> latest-snapshot (protected branch hook declined)
error: failed to push some refs to 'https://github.com/iree-org/iree.git'
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/40bf560[9](https://github.com/iree-org/iree/actions/runs/3144499996/jobs/5110632751#step:4:10)36a8022e68a3c00e7d2abefaf01305a6/start.js:9:19)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:[10](https://github.com/iree-org/iree/actions/runs/3144499996/jobs/5110632751#step:4:11)22:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/40bf560936a8022e68a3c00e7d2abefaf0[13](https://github.com/iree-org/iree/actions/runs/3144499996/jobs/5110632751#step:4:14)05a6/start.js:9:19)
    at ChildProcess.emit (events.js:3[14](https://github.com/iree-org/iree/actions/runs/3144499996/jobs/5110632751#step:4:15):20)
    at maybeClose (internal/child_process.js:1022:[16](https://github.com/iree-org/iree/actions/runs/3144499996/jobs/5110632751#step:4:17))
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```

Also, for some reason, the branch is diverged from `main`, which is really weird. It probably needs a manual force update to clean up this branch.

### What component(s) does this issue relate to?

Other

### Version information

Stopped working since `candidate-20220920.272`

https://github.com/iree-org/iree/actions/runs/3090947136/jobs/5000444104

**Comment by GMNGeoffrey** [comment]
Yes for some reason these diverged

```shell
$ git log --graph latest-snapshot...main --oneline --boundary
...
* | | 4cbcaaf28 Add elementwise fusion on multiuse ops (#10446)
* | | 46dc79cc7 Don't promote matmul for gemv kind of case (#10477)
* | | 32e8a8940 Generalize Transpose to Support 3D Shapes with Batch Dimensions (#10393)
* | | 5c8c00c39 Add new models to compare against TFLite (#10421)
| | | * e5c71f8fc (upstream/latest-snapshot, latest-snapshot) forgot to delete old stuff
| | | * 9cdc4e8f7 Rationalize architecture checks in ukernels.
| |_|/  
|/| |   
o | | 4a003840c detect cpu features on Apple/ARM64 (#10469)
 / /  
| o a930860b5 Integrate llvm-project at https://github.com/llvm/llvm-project/commit/42a90e6017b0 (#10453)
|/  
o 8d1e6abc3 Support GEMM Pipelining *without* Epilogue Peeling (#10388)


```

**Comment by GMNGeoffrey** [comment]
I'm guessing someone accidentally pushed to it (probably Benoit based on the commits). The branch protection on that does not look very thorough. Let me fix that also

**Comment by GMNGeoffrey** [comment]
Manually force-pushed to 95b50063b5339643d177363a46112c967f4c67db, the commit that should've been pushed by the latest run https://github.com/iree-org/iree/actions/runs/3152330874/jobs/5127441528. Will update the branch protection now so that only the bot can push to it (admins can change the settings for break glass, as I just did)
