### ISSUE TITLE
`iree-tflite-import` seems to have an error when lowering to TOSA

### ISSUE THREAD

**Issue by MaheshRavishankar** [iree-org/iree#10748]
#10740 seems to be hitting some error when lowering from TFLite to TOSA.

These are the failing tests.

Deeplabv3 with benchmark runs

```
FAILED: benchmark_suites/TFLite/deeplabv3.tflite.mlir /work/build-benchmarks/benchmark_suites/TFLite/deeplabv3.tflite.mlir 
cd /work/build-benchmarks/benchmarks/TFLite && /work/iree-tf-binaries/iree-import-tflite /work/build-benchmarks/benchmark_suites/TFLite/deeplabv3.tflite -o=/work/build-benchmarks/benchmark_suites/TFLite/deeplabv3.tflite.mlir
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /work/iree-tf-binaries/iree-import-tflite /work/build-benchmarks/benchmark_suites/TFLite/deeplabv3.tflite -o=/work/build-benchmarks/benchmark_suites/TFLite/deeplabv3.tflite.mlir
 #0 0x000000000c8fe8b2 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/work/iree-tf-binaries/iree-import-tflite+0xc8fe8b2)
 #1 0x000000000c8fca05 llvm::sys::RunSignalHandlers() (/work/iree-tf-binaries/iree-import-tflite+0xc8fca05)
 #2 0x000000000c8fec21 SignalHandler(int) (/work/iree-tf-binaries/iree-import-tflite+0xc8fec21)
 #3 0x00007fe7b6f14980 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12980)
 #4 0x0000000002f689a5 mlir::tosa::convertResizeOp(mlir::PatternRewriter&, mlir::Operation*, mlir::RankedTensorType, mlir::Value, llvm::StringRef, bool, bool) (/work/iree-tf-binaries/iree-import-tflite+0x2f689a5)
 #5 0x0000000002f36db2 mlir::tosa::(anonymous namespace)::ConvertTFLResizeBilinearOp::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&) const (/work/iree-tf-binaries/iree-import-tflite+0x2f36db2)
 #6 0x000000000c13b014 mlir::PatternApplicator::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&, llvm::function_ref<bool (mlir::Pattern const&)>, llvm::function_ref<void (mlir::Pattern const&)>, llvm::function_ref<mlir::LogicalResult (mlir::Pattern const&)>) (/work/iree-tf-binaries/iree-import-tflite+0xc13b014)
 #7 0x000000000c11450d mlir::applyPatternsAndFoldGreedily(llvm::MutableArrayRef<mlir::Region>, mlir::FrozenRewritePatternSet const&, mlir::GreedyRewriteConfig) (/work/iree-tf-binaries/iree-import-tflite+0xc11450d)
 #8 0x0000000002f7e560 mlir::tosa::ApplyPatternsWithShapeResolution(mlir::func::FuncOp, mlir::FrozenRewritePatternSet const&) (/work/iree-tf-binaries/iree-import-tflite+0x2f7e560)
 #9 0x0000000002ebf674 mlir::tosa::(anonymous namespace)::LegalizeTFTFL::runOnOperation() (/work/iree-tf-binaries/iree-import-tflite+0x2ebf674)
#10 0x000000000c297937 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (/work/iree-tf-binaries/iree-import-tflite+0xc297937)
#11 0x000000000c297d66 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (/work/iree-tf-binaries/iree-import-tflite+0xc297d66)
#12 0x000000000c29c2ed mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::$_12::operator()(mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo&) const (/work/iree-tf-binaries/iree-import-tflite+0xc29c2ed)
#13 0x000000000c29c12c mlir::LogicalResult mlir::failableParallelForEach<__gnu_cxx::__normal_iterator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo*, std::vector<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo, std::allocator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo> > >, mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::$_12&>(mlir::MLIRContext*, __gnu_cxx::__normal_iterator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo*, std::vector<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo, std::allocator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo> > >, __gnu_cxx::__normal_iterator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo*, std::vector<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo, std::allocator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo> > >, mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::$_12&) (/work/iree-tf-binaries/iree-import-tflite+0xc29c12c)
#14 0x000000000c299006 mlir::detail::OpToOpPassAdaptor::runOnOperation() (/work/iree-tf-binaries/iree-import-tflite+0xc299006)
Floating point exception (core dumped)
```

The following TFLite tests fail with the same error
```
Failed Tests (3):
  TENSORFLOW_TESTS :: iree_tfl_tests/cartoon_gan.run
  TENSORFLOW_TESTS :: iree_tfl_tests/east_text_detector.run
  TENSORFLOW_TESTS :: iree_tfl_tests/llvmcpu_posenet_i8.run

```

```
[  FAILED  ] CartoonGanTest.test_compile_tflite
======================================================================
ERROR: test_compile_tflite (__main__.CartoonGanTest)
CartoonGanTest.test_compile_tflite
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/integrations/tensorflow/test/python/iree_tfl_tests/cartoon_gan_test.py", line 19, in test_compile_tflite
    self.compile_and_execute()
  File "/work/integrations/tensorflow/test/python/iree_tfl_tests/test_util.py", line 149, in compile_and_execute
    import_only=False)
  File "/work/full-build-dir/compiler/bindings/python/iree/compiler/tools/tflite.py", line 154, in compile_file
    result = invoke_pipeline([import_cl, compile_cl])
  File "/work/full-build-dir/compiler/bindings/python/iree/compiler/tools/binaries.py", line 259, in invoke_pipeline
    raise CompilerToolError(stage.completed)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile
Diagnostics:
/tmp/lit/iree_tfl_tests/Output/cartoon_gan.run.tmp/download/model.mlirbc:0:0: error: 'tosa.resize' op requires attribute 'offset_fp'
/tmp/lit/iree_tfl_tests/Output/cartoon_gan.run.tmp/download/model.mlirbc:0:0: note: in bytecode version 0 produced by: MLIR16.0.0git


Invoked with:
 iree-compile /work/full-build-dir/compiler/bindings/python/iree/compiler/tools/../_mlir_libs/iree-compile - --iree-input-type=tosa --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=llvm-cpu -o=/tmp/lit/iree_tfl_tests/Output/cartoon_gan.run.tmp/download/module.vmfb --iree-llvm-embedded-linker-path=/work/full-build-dir/compiler/bindings/python/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
```

**Comment by MaheshRavishankar** [comment]
Assigning to Rob since he is already looking at it.

**Comment by rsuderman** [comment]
Fixed and verified.
