### ISSUE TITLE
[JAX + IREE | Apple M1 Max] - Fails to legalize 'math.roundeven'

### ISSUE THREAD

**Issue by lausena** [iree-org/iree#10938]
### What happened?

Using jax + iree Mac M1 Max fails call to `round()` on a a jax DeviceArray(). 

### Steps to reproduce your issue

1. Create a _DeviceArray(), let's say its called dArr
2. Call round on `dArr.round()`
3. See error

```
>>> x
DeviceArray([[1., 2.],
             [3., 4.]], dtype=float32)
>>> x.round()

......

{CompilerToolError}Error invoking IREE compiler tool iree-compile
Diagnostics:
<string>:1:0: error: failed to legalize operation 'math.roundeven'
<string>:1:0: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"vulkan", "vulkan-spirv-fb", {spirv.target_env = #spirv.target_env<#spirv.vce<v1.3, [Shader, Float16, Int64, Int16, Int8, StorageBuffer16BitAccess, StorageUniform16, StoragePushConstant16, StorageBuffer8BitAccess, UniformAndStorageBuffer8BitAccess, StoragePushConstant8, GroupNonUniform, GroupNonUniformVote, GroupNonUniformArithmetic, GroupNonUniformBallot, GroupNonUniformShuffle, GroupNonUniformShuffleRelative, GroupNonUniformQuad, VariablePointers, VariablePointersStorageBuffer], [SPV_KHR_16bit_storage, SPV_KHR_8bit_storage, SPV_KHR_storage_buffer_storage_class, SPV_KHR_variable_pointers]>, Apple:IntegratedGPU, #spirv.resource_limits<max_compute_shared_memory_size = 32768, max_compute_workgroup_invocations = 1024, max_compute_workgroup_si...
```

Also happens to jnp.linalg.inv(x) where the error is:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lausena/developer/repos/jax/jax/_src/iree.py", line 186, in compile
    iree_binary = iree.compiler.compile_str(
  File "/Users/lausena/miniforge3/envs/tfpy310/lib/python3.10/site-packages/iree/compiler/tools/core.py", line 278, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/Users/lausena/miniforge3/envs/tfpy310/lib/python3.10/site-packages/iree/compiler/tools/binaries.py", line 196, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile
Diagnostics:
<stdin>:1:0: error: 'mhlo.scatter' op expects bounds of the scatter dimensions of updates to be same as the bounds of the corresponding dimensions of scatter indices. For scatter dimension 1, updates bound is 2 , scatter_indices bound is 1.
compilation failed
```

### Version information

M1 Max | Darwin 22.1.0

JAX compiled with the following extra_args ` extra_args += ["--iree-llvm-target-triple=arm64-apple-darwin22.1.0", "--iree-flow-demote-i64-to-i32", "--iree-vulkan-target-triple=m1-moltenvk-macos", "--iree-llvm-target-cpu-features=host", "--iree-mhlo-demote-i64-to-i32=true"]`

**Comment by antiagainst** [comment]
Yeah we are missing conversions from `math.roundeven` to SPIR-V. Should be straightforward given we have GLSL extended instruction `RoundEven`. Assigning to @kuhar to add it.

**Comment by kuhar** [comment]
This should be fixed when https://github.com/llvm/llvm-project/commit/c97035c49d941e5b196a938f0393f811d1adbd57 gets integrated
