### ISSUE TITLE
Stable Diffusion compiler crash for CPU (Linux) - FP16

### ISSUE THREAD

**Issue by powderluv** [iree-org/iree#11448]
### What happened?

Running stable diffusion FP16 on CPU crashes the IREE compiler. 

anush@anush-5900xt ~/github/SHARK
 % IREE_SAVE_TEMPS=save_tmps  python3.10 shark/examples/shark_inference/stable_diffusion/main.py --precision=fp16 --device=cpu --prompt="tajmahal, oil on canvas, sunflowers, 4k, uhd"

```
 % IREE_SAVE_TEMPS=save_tmps  python3.10 shark/examples/shark_inference/stable_diffusion/main.py --precision=fp16 --device
=cpu --prompt="tajmahal, oil on canvas, sunflowers, 4k, uhd"                                                              
shark_tank local cache is located at /home/anush/.local/shark_tank/ . You may change this by setting the --local_tank_cach
e= pytest flag                                                                                                            
The models are present in the /home/anush/.local/shark_tank/. If you want a fresh                                         
                download, consider deleting the directory.                                                                
Copying gs://shark_tank/prashant_nod/unet_23nov_fp16_torch/hash.npy...                                                    
/ [1 files][  640.0 B/  640.0 B]                                                                                          
Operation completed over 1 objects/640.0 B.                                                                               
No vmfb found. Compiling and saving to /home/anush/github/SHARK/unet_23nov_fp16_cpu.vmfb                                  
Target triple found:x86_64-linux-gnu                                                                                      
Traceback (most recent call last):                                                                                        
  File "/home/anush/github/SHARK/shark/examples/shark_inference/stable_diffusion/main.py", line 59, in <module>           
    unet = get_unet()                                                                                                     
  File "/home/anush/github/SHARK/shark/examples/shark_inference/stable_diffusion/opt_params.py", line 39, in get_unet     
    return get_shark_model(bucket, model_name, iree_flags)                                                                
  File "/home/anush/github/SHARK/shark/examples/shark_inference/stable_diffusion/utils.py", line 50, in get_shark_model   
    return _compile_module(shark_module, model_name, extra_args)                                                          
  File "/home/anush/github/SHARK/shark/examples/shark_inference/stable_diffusion/utils.py", line 31, in _compile_module       path = shark_module.save_module(                                                                                        File "/home/anush/github/SHARK/shark/shark_inference.py", line 188, in save_module                                      
    return export_iree_module_to_vmfb(                                                                                    
  File "/home/anush/github/SHARK/shark/iree_utils/compile_utils.py", line 303, in export_iree_module_to_vmfb              
    flatbuffer_blob = compile_module_to_flatbuffer(                                                                       
  File "/home/anush/github/SHARK/shark/iree_utils/compile_utils.py", line 246, in compile_module_to_flatbuffer                flatbuffer_blob = ireec.compile_str(                                                                                    File "/home/anush/github/SHARK/shark.venv/lib/python3.10/site-packages/iree/compiler/tools/core.py", line 278, in compile_str                                                                                                                         result = invoke_immediate(cl, immediate_input=input_bytes)                                                              File "/home/anush/github/SHARK/shark.venv/lib/python3.10/site-packages/iree/compiler/tools/binaries.py", line 196, in invoke_immediate                                                                                                            
    raise CompilerToolError(process)                                                                                      
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile
Diagnostics:
LLVM ERROR: Cannot select: 0x7feda0b55e80: v16f16 = X86ISD::FMAX 0x7feda4e8d910, 0x7feda4e9b280
  0x7feda4e8d910: v16f16 = bitcast 0x7feda3c6dbf0
    0x7feda3c6dbf0: v32i8 = X86ISD::BLENDV 0x7feda4e8d4b0, 0x7feda3c536d0, 0x7feda4e8d520
      0x7feda4e8d4b0: v32i8 = bitcast 0x7feda5961ac0
        0x7feda5961ac0: v16i16 = insert_subvector 0x7feda5961a50, 0x7fed9be424f0, Constant:i64<8>
          0x7feda5961a50: v16i16 = insert_subvector undef:v16i16, 0x7fed9be42870, Constant:i64<0>
            0x7feda4e9c860: v16i16 = undef
            0x7fed9be42870: v8i16 = X86ISD::PINSRW 0x7fed9be42790, 0x7fed9be28080, TargetConstant:i8<7>
              0x7fed9be42790: v8i16 = X86ISD::PINSRW 0x7fed9be42720, 0x7fed9be27ec0, TargetConstant:i8<6>
                0x7fed9be42720: v8i16 = X86ISD::PINSRW 0x7fed9be426b0, 0x7fed9be27d00, TargetConstant:i8<5>
                  0x7fed9be426b0: v8i16 = X86ISD::PINSRW 0x7fed9be42640, 0x7fed9be27b40, TargetConstant:i8<4>


.....


              0x7feda4e57ad0: v32i8 = bitcast 0x7feda0b22d80
                0x7feda0b22d80: v16f16 = X86ISD::FMAX 0x7feda4ddad50, 0x7feda4e51cc0
                  0x7feda4ddad50: v16f16 = bitcast 0x7feda3c3e3a0

                  0x7feda4e51cc0: v16f16 = bitcast 0x7feda3c52710

In function: forward_dispatch_52_generic_16x4096x4096
<unknown>:0: error: Failures have been detected while processing an MLIR pass pipeline
<unknown>:0: note: Pipeline failed while executing [`mlir::iree_compiler::IREE::HAL::SerializeExecutablesPass` on 'hal.executable' operation: @llvm_module_linked_llvm_cpu, `mlir::iree_compiler::IREE::HAL::SerializeTargetExecutablesPass` on 'hal.executable' operation: @llvm_module_linked_llvm_cpu]: reproducer generated at `save_tmps/core-reproducer.mlir`


Invoked with:
 iree-compile /home/anush/github/SHARK/shark.venv/lib/python3.10/site-packages/iree/compiler/tools/../_mlir_libs/iree-compile - --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=llvm-cpu --iree-llvm-embedded-linker-path=/home/anush/github/SHARK/shark.venv/lib/python3.10/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --mlir-pass-pipeline-crash-reproducer=save_tmps/core-reproducer.mlir --iree-llvm-target-cpu-features=host -iree-llvm-target-triple=x86_64-linux-gnu --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-util-zero-fill-elided-attrs --iree-flow-enable-padding-linalg-ops --iree-flow-linalg-ops-padding-size=32 --iree-flow-enable-conv-img2col-transform

Need more information? Set IREE_SAVE_TEMPS=/some/dir in your environment to save all artifacts and reproducers.

```

**Comment by jpienaar** [comment]
I don't think FP16 proper is supported on CPU (X86ISD::FMAX failing to match), does this work with f32?

**Comment by allieculp** [comment]
@powderluv @hanhanW Is this still an active issue?

**Comment by hanhanW** [comment]
I haven't looked into the bug yet, @powderluv might have more context.

**Comment by allieculp** [comment]
@powderluv Bumping this one up again - still active?

**Comment by allieculp** [comment]
@powderluv moving to backlog please let us know if this is still active.

**Comment by hanhanW** [comment]
Closing as stale
