### ISSUE TITLE
Assert firing in llvm::ArrayRef<long>::slice for tensor.insert_slice op

### ISSUE THREAD

**Issue by c-rhodes** [iree-org/iree#11947]
### What happened?

Hitting this assert for a `tensor.insert_slice` op
```iree-compile: iree/third_party/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:195: llvm::ArrayRef<T> llvm::ArrayRef<T>::slice(size_t, size_t) const [with T = long int; size_t = long unsigned int]: Assertion `N+M <= size() && "Invalid specifier"' failed.```
**full backtrace**
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x0000ffffe7026a14 in __GI_abort () at abort.c:79
#2  0x0000ffffe703338c in __assert_fail_base (fmt=0xffffe712c8a8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0xffffe7b0dc00 "N+M <= size() && \"Invalid specifier\"",
    file=file@entry=0xffffe7b0a6e8 "iree/third_party/llvm-project/llvm/include/llvm/ADT/ArrayRef.h", line=line@entry=195,
    function=function@entry=0xffffe7b0e4d8 "llvm::ArrayRef<T> llvm::ArrayRef<T>::slice(size_t, size_t) const [with T = long int; size_t = long unsigned int]") at assert.c:92
#3  0x0000ffffe70333f4 in __GI___assert_fail (assertion=0xffffe7b0dc00 "N+M <= size() && \"Invalid specifier\"", file=0xffffe7b0a6e8 "iree/third_party/llvm-project/llvm/include/llvm/ADT/ArrayRef.h", line=195,
    function=0xffffe7b0e4d8 "llvm::ArrayRef<T> llvm::ArrayRef<T>::slice(size_t, size_t) const [with T = long int; size_t = long unsigned int]") at assert.c:101
#4  0x0000ffffef5fc0c8 in llvm::ArrayRef<long>::slice (this=0xffffffffc3c8, N=3, M=1) at /home/culrho01/vosa/iree/third_party/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:195
#5  0x0000fffff6be7568 in computeTensorReshapeCollapsedType (type=..., reassociation=...) at /home/culrho01/vosa/iree/third_party/llvm-project/mlir/lib/Dialect/Tensor/IR/TensorOps.cpp:1288
#6  0x0000fffff6be7730 in mlir::tensor::CollapseShapeOp::build (b=..., result=..., src=..., reassociation=..., attrs=...) at /home/culrho01/vosa/iree/third_party/llvm-project/mlir/lib/Dialect/Tensor/IR/TensorOps.cpp:1308
#7  0x0000fffff3ce4330 in mlir::OpBuilder::create<mlir::tensor::CollapseShapeOp, mlir::detail::TypedValue<mlir::TensorType>, llvm::SmallVector<llvm::SmallVector<long, 2u>, 1u>&> (this=0xffffffffce98, location=...)
    at /home/culrho01/vosa/iree/third_party/llvm-project/mlir/include/mlir/IR/Builders.h:461
#8  0x0000fffff3cde330 in (anonymous namespace)::RankReducedInsertSliceOp<mlir::tensor::InsertSliceOp>::matchAndRewrite (this=0xaaaaab08c580, insertSliceOp=..., rewriter=...)
    at /home/culrho01/vosa/iree/third_party/llvm-project/mlir/lib/Dialect/Linalg/Transforms/DropUnitDims.cpp:645
#9  0x0000fffff3b44030 in mlir::detail::OpOrInterfaceRewritePatternBase<mlir::tensor::InsertSliceOp>::matchAndRewrite (this=0xaaaaab08c580, op=0xaaaaaabf07c0, rewriter=...) at /home/culrho01/vosa/iree/third_party/llvm-project/mlir/include/mlir/IR/PatternMatch.h:329
#10 0x0000fffff71fbe98 in mlir::PatternApplicator::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&, llvm::function_ref<bool (mlir::Pattern const&)>, llvm::function_ref<void (mlir::Pattern const&)>, llvm::function_ref<mlir::LogicalResult (mlir::Pattern const&)>)
    (this=0xffffffffceb8, op=0xaaaaaabf07c0, rewriter=..., canApply=..., onFailure=..., onSuccess=...) at /home/culrho01/vosa/iree/third_party/llvm-project/mlir/lib/Rewrite/PatternApplicator.cpp:200
#11 0x0000fffff7199d98 in (anonymous namespace)::GreedyPatternRewriteDriver::simplify (this=0xffffffffce90, regions=...) at /home/culrho01/vosa/iree/third_party/llvm-project/mlir/lib/Transforms/Utils/GreedyPatternRewriteDriver.cpp:274
#12 0x0000fffff719aae4 in mlir::applyPatternsAndFoldGreedily (regions=..., patterns=..., config=...) at /home/culrho01/vosa/iree/third_party/llvm-project/mlir/lib/Transforms/Utils/GreedyPatternRewriteDriver.cpp:417
#13 0x0000ffffef5f0e5c in mlir::applyPatternsAndFoldGreedily (op=0xaaaaaabf6340, patterns=..., config=...) at /home/culrho01/vosa/iree/third_party/llvm-project/mlir/include/mlir/Transforms/GreedyPatternRewriteDriver.h:71
#14 0x0000fffff3cd6b80 in (anonymous namespace)::LinalgFoldUnitExtentDimsPass::runOnOperation (this=0xaaaaab0ba520) at /home/culrho01/vosa/iree/third_party/llvm-project/mlir/lib/Dialect/Linalg/Transforms/DropUnitDims.cpp:688
#15 0x0000fffff72650ec in mlir::detail::OpToOpPassAdaptor::run (pass=0xaaaaab0ba520, op=0xaaaaaabf6340, am=..., verifyPasses=true, parentInitGeneration=1) at /home/culrho01/vosa/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:465
#16 0x0000fffff726535c in mlir::detail::OpToOpPassAdaptor::runPipeline (pm=..., op=0xaaaaaabf6340, am=..., verifyPasses=true, parentInitGeneration=1, instrumentor=0xaaaaaab9c8b0, parentInfo=0xffffffffd5c8)
    at /home/culrho01/vosa/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:529
#17 0x0000fffff7266324 in mlir::detail::OpToOpPassAdaptor::<lambda(mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo&)>::operator()(mlir::detail::OpToOpPassAdaptor::OpPMInfo &) const (__closure=0xffffffffd628, opInfo=...)
    at /home/culrho01/vosa/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:751
#18 0x0000fffff7268dc0 in mlir::failableParallelForEach<__gnu_cxx::__normal_iterator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo*, std::vector<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo> >, mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::<lambda(mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo&)>&>(mlir::MLIRContext *, __gnu_cxx::__normal_iterator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo*, std::vector<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo, std::allocator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo> > >, __gnu_cxx::__normal_iterator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo*, std::vector<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo, std::allocator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo> > >, mlir::detail::OpToOpPassAdaptor::<lambda(mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo&)> &) (context=0xaaaaaab74308, begin={passManagerIdx = 0, op = 0xaaaaaabf6340, am = {impl = 0xaaaaab08c3e0}}, end={passManagerIdx = 49, op = 0xe, am = {impl = 0xaaaaab1b2cb0}}, func=...)
    at /home/culrho01/vosa/iree/third_party/llvm-project/mlir/include/mlir/IR/Threading.h:46
#19 0x0000fffff7268018 in mlir::failableParallelForEach<std::vector<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo>&, mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::<lambda(mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo&)>&>(mlir::MLIRContext *, std::vector<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo, std::allocator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo> > &, mlir::detail::OpToOpPassAdaptor::<lambda(mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo&)> &) (context=0xaaaaaab74308, range=std::vector of length 1, capacity 1 = {...}, func=...) at /home/culrho01/vosa/iree/third_party/llvm-project/mlir/include/mlir/IR/Threading.h:92
#20 0x0000fffff72666e8 in mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl (this=0xaaaaaabf8e10, verifyPasses=true) at /home/culrho01/vosa/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:759
#21 0x0000fffff7265d80 in mlir::detail::OpToOpPassAdaptor::runOnOperation (this=0xaaaaaabf8e10, verifyPasses=true) at /home/culrho01/vosa/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:650
#22 0x0000fffff72650d0 in mlir::detail::OpToOpPassAdaptor::run (pass=0xaaaaaabf8e10, op=0xaaaaaab9f870, am=..., verifyPasses=true, parentInitGeneration=1) at /home/culrho01/vosa/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:463
#23 0x0000fffff726535c in mlir::detail::OpToOpPassAdaptor::runPipeline (pm=..., op=0xaaaaaab9f870, am=..., verifyPasses=true, parentInitGeneration=1, instrumentor=0x0, parentInfo=0x0) at /home/culrho01/vosa/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:529
#24 0x0000fffff7266d24 in mlir::PassManager::runPasses (this=0xaaaaaab9c818, op=0xaaaaaab9f870, am=...) at /home/culrho01/vosa/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:835
#25 0x0000fffff7266b7c in mlir::PassManager::run (this=0xaaaaaab9c818, op=0xaaaaaab9f870) at /home/culrho01/vosa/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:814
#26 0x0000ffffeecb8dd0 in mlir::iree_compiler::embed::(anonymous namespace)::Invocation::runPipeline (this=0xaaaaaab9c810, pipeline=IREE_COMPILER_PIPELINE_STD) at /home/culrho01/vosa/iree/compiler/src/iree/compiler/API2/Internal/Embed.cpp:351
#27 0x0000ffffeecb9ad0 in ireeCompilerInvocationPipeline (inv=0xaaaaaab9c810, pipeline=IREE_COMPILER_PIPELINE_STD) at /home/culrho01/vosa/iree/compiler/src/iree/compiler/API2/Internal/Embed.cpp:558
#28 0x0000ffffeecab884 in mlir::iree_compiler::<lambda(iree_compiler_source_t*)>::operator()(iree_compiler_source_t *) const (__closure=0xffffffffdf40, source=0xaaaaaab9c540) at /home/culrho01/vosa/iree/compiler/src/iree/compiler/Tools/iree_compile_lib.cc:191
#29 0x0000ffffeecac444 in mlir::iree_compiler::runIreecMain (argc=4, argv=0xffffffffeda8) at /home/culrho01/vosa/iree/compiler/src/iree/compiler/Tools/iree_compile_lib.cc:270
#30 0x0000ffffeecab234 in ireeCompilerRunMain (argc=4, argv=0xffffffffeda8) at /home/culrho01/vosa/iree/compiler/src/iree/compiler/API2/Internal/IREECompileToolEntryPoint.cpp:12
#31 0x0000aaaaaaab08e8 in main (argc=4, argv=0xffffffffeda8) at /home/culrho01/vosa/iree/tools/iree-compile-main.cc:9
```

### Steps to reproduce your issue

**Input**
```
// reproducer.mlir
func.func @foo(%arg0: tensor<1x1x32x2xi16>, %arg1: tensor<1x32x2xi16>) -> tensor<1x1x32x2xi16> {
  %inserted_slice = tensor.insert_slice %arg1 into %arg0[0, 0, 0, 0] [1, 1, 32, 2] [1, 1, 1, 1] : tensor<1x32x2xi16> into tensor<1x1x32x2xi16>
  return %inserted_slice : tensor<1x1x32x2xi16>
}
```
**Compile**
`iree-compile reproducer.mlir -o reproducer.vmfb`

### What component(s) does this issue relate to?

MLIR

### Version information

d782f54f5

**Comment by c-rhodes** [comment]
I reproduced the issue in standalone MLIR and filed another issue [there](https://github.com/llvm/llvm-project/issues/60291) with more info. I also have a [fix](https://reviews.llvm.org/D142557) but would like some input, @MaheshRavishankar please could you take a look? Should I close this issue?

**Comment by allieculp** [comment]
@MaheshRavishankar Bumping this back up for you - if not a priority right now we can set P2/3.

**Comment by MaheshRavishankar** [comment]
I am downgrading it for now... If this is still an issue, we can re-assign to someone who can fix it...
