### ISSUE TITLE
iree-build/runtime/setup.py exits with a TypeError

### ISSUE THREAD

**Issue by navdeepkk-polymagelabs** [iree-org/iree#12039]
### What happened?

Was trying to install the `iree-runtime` package with the commit `b77145db3` and ran into the following error:
```
Traceback (most recent call last):
  File "setup.py", line 363, in <module>
    setup(
  File "/home1/navdeep/iree.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
    _install_setup_requires(attrs)
  File "/home1/navdeep/iree.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 75, in _install_setup_requires
    dist = MinimalDistribution(attrs)
  File "/home1/navdeep/iree.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 57, in __init__
    super().__init__(filtered)
  File "/home1/navdeep/iree.venv/lib/python3.8/site-packages/setuptools/dist.py", line 473, in __init__
    for ep in metadata.entry_points(group='distutils.setup_keywords'):
  File "/home1/navdeep/iree.venv/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 999, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/home1/navdeep/iree.venv/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 449, in load
    ordered = sorted(eps, key=by_group)
  File "/home1/navdeep/iree.venv/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 996, in <genexpr>
    eps = itertools.chain.from_iterable(
  File "/home1/navdeep/iree.venv/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
  File "/home1/navdeep/iree.venv/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 931, in _normalized_name
    return self._name_from_stem(stem) or super()._normalized_name
  File "/home1/navdeep/iree.venv/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 600, in _normalized_name
    return Prepared.normalize(self.name)
  File "/home1/navdeep/iree.venv/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 855, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
  File "/usr/lib/python3.8/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
```

### Steps to reproduce your issue

Followed these steps to build the bindings. https://iree-org.github.io/iree/building-from-source/python-bindings-and-importers/#building-python-bindings and then went on to install the packages.

### What component(s) does this issue relate to?

Python, Runtime

### Version information

b77145db3

**Comment by navdeepkk-polymagelabs** [comment]
This is actually working. Apologies for the spam.
