### ISSUE TITLE
SEGV at embedded_elf_loader.c:305 when compiling ssd_mobilenet_v2_dynamic_1.0_float

### ISSUE THREAD

**Issue by dcaballe** [iree-org/iree#12083]
This issue happens with asan enabled:

```
wget https://storage.googleapis.com/iree-model-artifacts/ssd_mobilenet_v2_dynamic_1.0_float.tflite
iree-import-tflite ssd_mobilenet_v2_dynamic_1.0_float.tflite --output-format=mlir-ir -o ssd_mobilenet_v2_dynamic_1.0_float.mlir
iree-benchmark-module --device=local-task --module=mobilenet_float.vmfb --function=main --input=1x244x244x3xf32 --task_topology_group_count=8 --device_allocator=caching --device_allocator=caching --time_unit=ns --benchmark_repetitions=10
```

```
==682945==ERROR: AddressSanitizer: SEGV on unknown address 0x7fbf76858000 (pc 0x7fbf76874682 bp 0x7fbf76a52920 sp 0x7fbf76a52868 T7)
==682945==The signal is caused by a WRITE memory access.
    #0 0x7fbf76874682  (<unknown module>)
    #1 0x555cff5f00e6 in iree_hal_elf_executable_issue_call /usr/local/google/home/diegocaballero/iree2/runtime/src/iree/hal/local/loaders/embedded_elf_loader.c:305:13
    #2 0x555cff54da4c in iree_task_dispatch_shard_execute /usr/local/google/home/diegocaballero/iree2/runtime/src/iree/task/task.c:800:11
    #3 0x555cff54face in iree_task_worker_execute /usr/local/google/home/diegocaballero/iree2/runtime/src/iree/task/worker.c:188:7
    #4 0x555cff54face in iree_task_worker_pump_once /usr/local/google/home/diegocaballero/iree2/runtime/src/iree/task/worker.c:249:3
    #5 0x555cff54face in iree_task_worker_pump_until_exit /usr/local/google/home/diegocaballero/iree2/runtime/src/iree/task/worker.c:298:12
    #6 0x555cff54face in iree_task_worker_main /usr/local/google/home/diegocaballero/iree2/runtime/src/iree/task/worker.c:376:5
    #7 0x555cff5696cb in iree_thread_start_routine /usr/local/google/home/diegocaballero/iree2/runtime/src/iree/base/internal/threading_pthreads.c:130:29

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (<unknown module>) 
Thread T7 created by T0 here:
    #0 0x555cff3cd42c in pthread_create (/usr/local/google/home/diegocaballero/iree2/build/debug/tools/iree-benchmark-module+0x18742c) (BuildId: 0c7dbdd371f4ac15)
    #1 0x555cff568c62 in iree_thread_create /usr/local/google/home/diegocaballero/iree2/runtime/src/iree/base/internal/threading_pthreads.c:180:10
    #2 0x555cff54f3e6 in iree_task_worker_initialize /usr/local/google/home/diegocaballero/iree2/runtime/src/iree/task/worker.c:67:26
    #3 0x555cff5445e2 in iree_task_executor_create /usr/local/google/home/diegocaballero/iree2/runtime/src/iree/task/executor.c:146:16
    #4 0x555cff543647 in iree_task_executors_create_from_flags /usr/local/google/home/diegocaballero/iree2/runtime/src/iree/task/api.c:336:14
    #5 0x555cff537150 in iree_hal_local_task_driver_factory_try_create /usr/local/google/home/diegocaballero/iree2/runtime/src/iree/hal/drivers/local_task/registration/driver_module.c:50:3
    #6 0x555cff5128d4 in iree_hal_driver_registry_try_create /usr/local/google/home/diegocaballero/iree2/runtime/src/iree/hal/driver_registry.c:316:14
    #7 0x555cff512a7a in iree_hal_create_device /usr/local/google/home/diegocaballero/iree2/runtime/src/iree/hal/driver_registry.c:344:3
    #8 0x555cff50eacf in iree_hal_create_device_from_flags /usr/local/google/home/diegocaballero/iree2/runtime/src/iree/tooling/device_util.c:605:3
    #9 0x555cff509fa6 in iree_tooling_load_hal_async_module /usr/local/google/home/diegocaballero/iree2/runtime/src/iree/tooling/context_util.c:113:3
    #10 0x555cff509fa6 in iree_tooling_resolve_module_dependency /usr/local/google/home/diegocaballero/iree2/runtime/src/iree/tooling/context_util.c:315:5
    #11 0x555cff6289ea in iree_vm_bytecode_module_enumerate_dependencies /usr/local/google/home/diegocaballero/iree2/runtime/src/iree/vm/bytecode_module.c:531:5
    #12 0x555cff50928e in iree_tooling_resolve_modules /usr/local/google/home/diegocaballero/iree2/runtime/src/iree/tooling/context_util.c:379:14
    #13 0x555cff50ad3d in iree_tooling_create_context_from_flags /usr/local/google/home/diegocaballero/iree2/runtime/src/iree/tooling/context_util.c:461:3
    #14 0x555cff421981 in iree::(anonymous namespace)::IREEBenchmark::Init() /usr/local/google/home/diegocaballero/iree2/tools/iree-benchmark-module-main.cc:461:5
    #15 0x555cff421981 in iree::(anonymous namespace)::IREEBenchmark::Register() /usr/local/google/home/diegocaballero/iree2/tools/iree-benchmark-module-main.cc:437:7
    #16 0x555cff421981 in main /usr/local/google/home/diegocaballero/iree2/tools/iree-benchmark-module-main.cc:588:41
    #17 0x7fbf77246189 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
```

**Comment by hanhanW** [comment]
Hey @dcaballe , it looks like a codegen issue. I don't have much context about the model. Could you help triage this?

**Comment by dcaballe** [comment]
I would really appreciate some help as I've been [reporting ](https://github.com/issues?q=is%3Aissue+is%3Aopen+author%3A%40me+archived%3Afalse+sort%3Aupdated-desc)and root-causing multiple issues full time for a week. Would you have cycles to help?

**Comment by hanhanW** [comment]
Thanks for reporting and root-causing those issues! As I'm just back to work, I'm still catching up with what's happening and addressing other issues. I won't have cycles in the next few days. I can help when I got some cycles. Could you paste the compilation flags? E.g., what's the target triple to reproduce the issue? Is it default?

Also, would @vmurali have cycles to help triaging it? IMO, it would be a good opportunity to get more familiar with the e2e compilation stack.

**Comment by hanhanW** [comment]
I narrowed it down to a single op. It seems like an issue for dynamic concat cases.

```mlir
module {
  func.func @foo(%arg0: tensor<1x?x91xf32>, %arg1: tensor<1x?x91xf32>, %arg2: tensor<1x?x91xf32>, %arg3: tensor<1x?x91xf32>, %arg4: tensor<1x?x91xf32>, %arg5: tensor<1x?x91xf32>, %arg6: tensor<1x?x91xf32>) -> tensor<1x?x91xf32> {
    %0 = "tosa.concat"(%arg0, %arg1, %arg2, %arg4, %arg5, %arg6) {axis = 1 : i64} : (tensor<1x?x91xf32>, tensor<1x?x91xf32>, tensor<1x?x91xf32>, tensor<1x?x91xf32>, tensor<1x?x91xf32>, tensor<1x?x91xf32>) -> tensor<1x?x91xf32>
    return %0 : tensor<1x?x91xf32>
  }
}
```

To repro:

```
$ iree-compile --output-format=vm-bytecode --iree-hal-target-backends=llvm-cpu ~/repro.mlir -o /tmp/b.vmfb --iree-input-type=tosa --iree-llvm-sanitize=address --iree-llvm-link-embedded=false
$ iree-run-module --module=/tmp/b.vmfb --device=local-sync --function=foo --input=1x244x91xf32 --input=1x244x91xf32 --input=1x244x91xf32 --input=1x244x91xf32 --input=1x244x91xf32 --input=1x244x91xf32 --input=1x244x91xf32
```

note: I can only reproduced it with ASAN. It looks like there are issues in codegen.

**Comment by allieculp** [comment]
@hanhanW Setting as a P2 'in progress' - please update here if needed.

**Comment by hanhanW** [comment]
Closing as stale
