### ISSUE TITLE
Failed to import posenet_i8 model after 3-8-2023 integrate

### ISSUE THREAD

**Issue by vmurali** [iree-org/iree#12593]
`tfl.pack` operations still remain after importing.

Take a look at this error: https://github.com/openxla/iree/actions/runs/4386475586/jobs/7680966058

**Comment by vmurali** [comment]
The integrate PR is here: https://github.com/openxla/iree/pull/12562

**Comment by ScottTodd** [comment]
Can you/someone update the issue title and body to reflect what the actual failure was? This issue isn't very searchable at the moment, since it requires clicking through a few URLs to even see what failed and why.

**Comment by vmurali** [comment]
Snippets of the error:

```
I0310 16:59:17.389102 139656058431296 test_util.py:50] Saving compilation artifacts and traces to '/tmp/lit/iree_tfl_tests/Output/llvmcpu_posenet_i8.run.tmp/download'
I0310 16:59:17.515717 139656058431296 test_util.py:141] Setting up for IREE
I0310 16:59:17.516942 139656058431296 binaries.py:216] Invoke IREE Pipeline:
  /work/integrations/tensorflow/python_projects/iree_tflite/iree/tools/tflite/iree-import-tflite /tmp/lit/iree_tfl_tests/Output/llvmcpu_posenet_i8.run.tmp/download/model.mlirbc --mlir-print-debuginfo --save-temp-tfl-input=/tmp/lit/iree_tfl_tests/Output/llvmcpu_posenet_i8.run.tmp/download/tflite.mlirbc --save-temp-iree-input=/tmp/lit/iree_tfl_tests/Output/llvmcpu_posenet_i8.run.tmp/download/tosa.mlirbc
  /work/full-build-dir/compiler/bindings/python/iree/compiler/tools/../_mlir_libs/iree-compile - --iree-input-type=tosa --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=llvm-cpu -o=/tmp/lit/iree_tfl_tests/Output/llvmcpu_posenet_i8.run.tmp/download/module.vmfb --iree-llvmcpu-embedded-linker-path=/work/full-build-dir/compiler/bindings/python/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
[  FAILED  ] PosenetI8Test.test_compile_tflite
======================================================================
ERROR: test_compile_tflite (__main__.PosenetI8Test)
PosenetI8Test.test_compile_tflite
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/integrations/tensorflow/test/python/iree_tfl_tests/posenet_i8_test.py", line 47, in test_compile_tflite
    self.compile_and_execute()
  File "/work/integrations/tensorflow/test/python/iree_tfl_tests/test_util.py", line 149, in compile_and_execute
    import_only=False)
  File "/work/full-build-dir/compiler/bindings/python/iree/compiler/tools/tflite.py", line 154, in compile_file
    result = invoke_pipeline([import_cl, compile_cl])
  File "/work/full-build-dir/compiler/bindings/python/iree/compiler/tools/binaries.py", line 259, in invoke_pipeline
    raise CompilerToolError(stage.completed)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-import-tflite
Diagnostics:
/tmp/lit/iree_tfl_tests/Output/llvmcpu_posenet_i8.run.tmp/download/model.mlirbc:0:0: error: 'tfl.pack' op : illegal op still exists
/tmp/lit/iree_tfl_tests/Output/llvmcpu_posenet_i8.run.tmp/download/model.mlirbc:0:0: note: see current operation: %527 = "tfl.pack"(%522, %526) {axis = 2 : i32, values_count = 2 : i32} : (tensor<1x17xi8>, tensor<1x17xi8>) -> tensor<1x17x2xi8> loc("stack_3"("/tmp/lit/iree_tfl_tests/Output/llvmcpu_posenet_i8.run.tmp/download/model.mlirbc":0:0))
/tmp/lit/iree_tfl_tests/Output/llvmcpu_posenet_i8.run.tmp/download/model.mlirbc:0:0: error: 'tfl.pack' op : illegal op still exists
/tmp/lit/iree_tfl_tests/Output/llvmcpu_posenet_i8.run.tmp/download/model.mlirbc:0:0: note: see current operation: %399 = "tfl.pack"(%169, %391, %398) {axis = 1 : i32, values_count = 3 : i32} : (tensor<1xi32>, tensor<1xi32>, tensor<1xi32>) -> tensor<1x3xi32> loc("stack"("/tmp/lit/iree_tfl_tests/Output/llvmcpu_posenet_i8.run.tmp/download/model.mlirbc":0:0))
/tmp/lit/iree_tfl_tests/Output/llvmcpu_posenet_i8.run.tmp/download/model.mlirbc:0:0: error: 'tfl.pack' op : illegal op still exists
/tmp/lit/iree_tfl_tests/Output/llvmcpu_posenet_i8.run.tmp/download/model.mlirbc:0:0: note: see current operation: %503 = "tfl.pack"(%170, %495, %502) {axis = 1 : i32, values_count = 3 : i32} : (tensor<17xi32>, tensor<17xi32>, tensor<17xi32>) -> tensor<17x3xi32> loc("stack_1"("/tmp/lit/iree_tfl_tests/Output/llvmcpu_posenet_i8.run.tmp/download/model.mlirbc":0:0))
/tmp/lit/iree_tfl_tests/Output/llvmcpu_posenet_i8.run.tmp/download/model.mlirbc:0:0: error: The following illegal operations still remain: 
	tfl.pack (count: 3)

Running iree-import-tflite pass pipeline failed (see diagnostics)


Invoked with:
 iree-import-tflite /work/integrations/tensorflow/python_projects/iree_tflite/iree/tools/tflite/iree-import-tflite /tmp/lit/iree_tfl_tests/Output/llvmcpu_posenet_i8.run.tmp/download/model.mlirbc --mlir-print-debuginfo --save-temp-tfl-input=/tmp/lit/iree_tfl_tests/Output/llvmcpu_posenet_i8.run.tmp/download/tflite.mlirbc --save-temp-iree-input=/tmp/lit/iree_tfl_tests/Output/llvmcpu_posenet_i8.run.tmp/download/tosa.mlirbc

```

**Comment by hanhanW** [comment]
Adding more context from Discord... According to @rsuderman mentioned on discord, the fix was landed in tensorflow repo. We can either cherry-pick it in or wait for the next integrate. The conclusion is waiting for the next integrate.

**Comment by hanhanW** [comment]
fixed by the previous integrate
