### ISSUE TITLE
heap-buffer-overflow in iree_task_pool_grow on Arm Ubuntu-22.04

### ISSUE THREAD

**Issue by per** [iree-org/iree#12853]
### What happened?

Running ctests on AArch64 machine with Ubuntu 22.04 causes tests to fail and timeout.
Enabling ASAN reveals that the bug is a heap-buffer-overflow which has been reported [before](https://github.com/openxla/iree/issues/9953).

### Steps to reproduce your issue

1. Follow the build instructions and build on Ubuntu 22.04 on an AArch64 machine.
2. Enable ASAN, build and run tests.
3. ```ctest -C RelWithDebInfo -T test --output-on-failure```
4. ASAN catches the heap-buffer-overflow

### What component(s) does this issue relate to?

Runtime

### Version information

Tested at dea9b6b0a6655d69e6ff7ccb6bf639331e3c6cbd

```
Ubuntu clang version 14.0.0-1ubuntu1
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

```
Ubuntu clang version 15.0.6
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

### Additional context

ASAN output:

```
  ==244140==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xffffa8d02500 at pc 0xaaaac986050c bp 0xffffcf9ec450 sp 0xffffcf9ec448
WRITE of size 8 at 0xffffa8d02500 thread T0
    #0 0xaaaac9860508 in iree_task_pool_grow /home/ubuntu/src/openxla/iree/runtime/src/iree/task/pool.c:100:53
    #1 0xaaaac9857d28 in (anonymous namespace)::PoolTest_Lifetime_Test::TestBody() /home/ubuntu/src/openxla/iree/runtime/src/iree/task/pool_test.cc:25:3
    #2 0xaaaac990f200 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/ubuntu/src/openxla/iree/third_party/googletest/googletest/src/gtest.cc:2621:10
    #3 0xaaaac990f200 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/ubuntu/src/openxla/iree/third_party/googletest/googletest/src/gtest.cc:2657:14
    #4 0xaaaac98c33e8 in testing::Test::Run() /home/ubuntu/src/openxla/iree/third_party/googletest/googletest/src/gtest.cc:2696:5
    #5 0xaaaac98c5f58 in testing::TestInfo::Run() /home/ubuntu/src/openxla/iree/third_party/googletest/googletest/src/gtest.cc:2845:11
    #6 0xaaaac98c78d8 in testing::TestSuite::Run() /home/ubuntu/src/openxla/iree/third_party/googletest/googletest/src/gtest.cc:3004:30
    #7 0xaaaac98f71c0 in testing::internal::UnitTestImpl::RunAllTests() /home/ubuntu/src/openxla/iree/third_party/googletest/googletest/src/gtest.cc:5889:44
    #8 0xaaaac991167c in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/ubuntu/src/openxla/iree/third_party/googletest/googletest/src/gtest.cc:2621:10
    #9 0xaaaac991167c in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/ubuntu/src/openxla/iree/third_party/googletest/googletest/src/gtest.cc:2657:14
    #10 0xaaaac98f66e8 in testing::UnitTest::Run() /home/ubuntu/src/openxla/iree/third_party/googletest/googletest/src/gtest.cc:5454:10
    #11 0xaaaac986de0c in RUN_ALL_TESTS() /home/ubuntu/src/openxla/iree/third_party/googletest/googletest/include/gtest/gtest.h:2310:73
    #12 0xaaaac986de0c in main /home/ubuntu/src/openxla/iree/runtime/src/iree/testing/gtest_main.cc:17:10
    #13 0xffffad0b73f8 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #14 0xffffad0b74c8 in __libc_start_main csu/../csu/libc-start.c:392:3
    #15 0xaaaac97a75ec in _start (/home/ubuntu/src/openxla/iree/build/runtime/src/iree/task/pool_test+0x475ec) (BuildId: 18b24cd96043e29477ccd44e3f8d17eef13c450e)

0xffffa8d02500 is located 0 bytes to the right of 4096-byte region [0xffffa8d01500,0xffffa8d02500)
allocated by thread T0 here:
    #0 0xaaaac981e97c in __interceptor_calloc (/home/ubuntu/src/openxla/iree/build/runtime/src/iree/task/pool_test+0xbe97c) (BuildId: 18b24cd96043e29477ccd44e3f8d17eef13c450e)
    #1 0xaaaac986a778 in iree_allocator_system_alloc /home/ubuntu/src/openxla/iree/runtime/src/iree/base/allocator.c:86:17
    #2 0xaaaac986a778 in iree_allocator_system_ctl /home/ubuntu/src/openxla/iree/runtime/src/iree/base/allocator.c:126:14
    #3 0xaaaac986a0a8 in iree_allocator_issue_alloc /home/ubuntu/src/openxla/iree/runtime/src/iree/base/allocator.c:27:10
    #4 0xaaaac986a0a8 in iree_allocator_malloc /home/ubuntu/src/openxla/iree/runtime/src/iree/base/allocator.c:32:10
    #5 0xaaaac98602bc in iree_task_pool_grow /home/ubuntu/src/openxla/iree/runtime/src/iree/task/pool.c:63:3
    #6 0xaaaac9857d28 in (anonymous namespace)::PoolTest_Lifetime_Test::TestBody() /home/ubuntu/src/openxla/iree/runtime/src/iree/task/pool_test.cc:25:3
    #7 0xaaaac990f200 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/ubuntu/src/openxla/iree/third_party/googletest/googletest/src/gtest.cc:2621:10
    #8 0xaaaac990f200 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/ubuntu/src/openxla/iree/third_party/googletest/googletest/src/gtest.cc:2657:14
    #9 0xaaaac98c33e8 in testing::Test::Run() /home/ubuntu/src/openxla/iree/third_party/googletest/googletest/src/gtest.cc:2696:5
    #10 0xaaaac98c5f58 in testing::TestInfo::Run() /home/ubuntu/src/openxla/iree/third_party/googletest/googletest/src/gtest.cc:2845:11
    #11 0xaaaac98c78d8 in testing::TestSuite::Run() /home/ubuntu/src/openxla/iree/third_party/googletest/googletest/src/gtest.cc:3004:30
    #12 0xaaaac98f71c0 in testing::internal::UnitTestImpl::RunAllTests() /home/ubuntu/src/openxla/iree/third_party/googletest/googletest/src/gtest.cc:5889:44
    #13 0xaaaac991167c in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/ubuntu/src/openxla/iree/third_party/googletest/googletest/src/gtest.cc:2621:10
    #14 0xaaaac991167c in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/ubuntu/src/openxla/iree/third_party/googletest/googletest/src/gtest.cc:2657:14
    #15 0xaaaac98f66e8 in testing::UnitTest::Run() /home/ubuntu/src/openxla/iree/third_party/googletest/googletest/src/gtest.cc:5454:10
    #16 0xaaaac986de0c in RUN_ALL_TESTS() /home/ubuntu/src/openxla/iree/third_party/googletest/googletest/include/gtest/gtest.h:2310:73
    #17 0xaaaac986de0c in main /home/ubuntu/src/openxla/iree/runtime/src/iree/testing/gtest_main.cc:17:10
    #18 0xffffad0b73f8 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #19 0xffffad0b74c8 in __libc_start_main csu/../csu/libc-start.c:392:3
    #20 0xaaaac97a75ec in _start (/home/ubuntu/src/openxla/iree/build/runtime/src/iree/task/pool_test+0x475ec) (BuildId: 18b24cd96043e29477ccd44e3f8d17eef13c450e)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/ubuntu/src/openxla/iree/runtime/src/iree/task/pool.c:100:53 in iree_task_pool_grow
Shadow bytes around the buggy address:
  0x200ff51a0450: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x200ff51a0460: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x200ff51a0470: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x200ff51a0480: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x200ff51a0490: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x200ff51a04a0:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x200ff51a04b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x200ff51a04c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x200ff51a04d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x200ff51a04e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x200ff51a04f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
```

**Comment by per** [comment]
I'm working on a fix together with a test case which will catch this even if ASAN is not enabled.

**Comment by per** [comment]
Needed to get #12684 going.

**Comment by allieculp** [comment]
@per Setting this to in progress, please update as needed!

**Comment by per** [comment]
https://github.com/openxla/iree/pull/13013 fixes this bug.
