### ISSUE TITLE
"Illegal op still exists" when trying to compile mlir produced by iree-import-tflite (gpt2)

### ISSUE THREAD

**Issue by dellis23** [iree-org/iree#13156]
### What happened?

Attempting to import gpt2 from huggingface using `iree-import-tflite` followed by compiling with iree gives the following error:

```shell
Traceback (most recent call last):
  File "/usr/local/google/home/danielellis/Downloads/gpt2/main.py", line 23, in <module>
    main()
  File "/usr/local/google/home/danielellis/Downloads/gpt2/main.py", line 10, in main
    vmfb = ireec.compile_str(mlir_bytecode,
  File "/usr/local/google/home/danielellis/venv.gpt2/lib/python3.10/site-packages/iree/compile
r/tools/core.py", line 278, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/usr/local/google/home/danielellis/venv.gpt2/lib/python3.10/site-packages/iree/compile
r/tools/binaries.py", line 196, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile
Diagnostics:
64.tflite:0:0: error: 'tosa.reshape' op : illegal op still exists
64.tflite:0:0: note: called from
64.tflite:0:0: error: 'tosa.mul' op : illegal op still exists
64.tflite:0:0: note: called from
64.tflite:0:0: error: 'tosa.reshape' op : illegal op still exists
64.tflite:0:0: note: called from
64.tflite:0:0: error: 'tosa.slice' op : illegal op still exists
64.tflite:0:0: note: called from
64.tflite:0:0: error: 'tosa.exp' op : illegal op still exists
# ...
64.tflite:0:0: error: The following illegal operations still remain:
        tosa.reshape (count: 808)
        tosa.mul (count: 234)
        tosa.slice (count: 612)
        tosa.exp (count: 12)
        tosa.fully_connected (count: 337)
        tosa.reduce_sum (count: 62)
        tosa.add (count: 99)
        tosa.sub (count: 62)
        tosa.reciprocal (count: 13)
        tosa.transpose (count: 348)
        tosa.const (count: 163)
        tosa.rsqrt (count: 25)
        tosa.concat (count: 36)
        tosa.pow (count: 12)
        tosa.tanh (count: 12)
        tosa.gather (count: 1)
Invoked with:
 iree-compile /usr/local/google/home/danielellis/venv.gpt2/lib/python3.10/site-packages/iree/compiler/tools/../_mlir_libs/iree-compile - --iree-input-type=tm_tensor --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=llvm-cpu --iree-llvm-embedded-linker-path=/usr/local/google/home/danielellis/venv.gpt2/lib/python3.10/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false

Need more information? Set IREE_SAVE_TEMPS=/some/dir in your environment to save all artifacts and reproducers.
```

### Steps to reproduce your issue

Download `64.tflite` from https://huggingface.co/gpt2/tree/main

```shell
wget https://huggingface.co/gpt2/resolve/main/64.tflite 
```

Convert to mlir bytecode:

```shell
iree-import-tflite 64.tflite  > 64.mlir
```

Compile to vmfb:

```python
import iree.compiler as ireec

with open('64.mlir', 'rb') as f:
        mlir_bytecode = f.read()

vmfb = ireec.compile_str(mlir_bytecode,
    target_backends=["llvm-cpu"],
    input_type=ireec.InputType.TM_TENSOR)
```

### What component(s) does this issue relate to?

Compiler

### Version information

```iree-compiler==20230228.444
iree-runtime==20230228.444```

### Additional context

_No response_

**Comment by dellis23** [comment]
Jacques mentioned I should be using `ireec.InputType.TOSA`

**Comment by ScottTodd** [comment]
See also https://github.com/openxla/iree/issues/10297
