### ISSUE TITLE
Python binding for runtime not working for Windows

### ISSUE THREAD

**Issue by nirvedhmeshram** [iree-org/iree#13236]
I followed the steps in the documentation in the end for this check
```
# Add the bindings/python paths to PYTHONPATH and use the API.
.env.bat
python -c "import iree.compiler"
python -c "import iree.runtime"
```
I am able to find iree.compile fine but for iree.runtime I get
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\SD\iree\build\runtime\bindings\python\iree\runtime\__init__.py", line 13, in <module>
    from . import _binding
  File "D:\SD\iree\build\runtime\bindings\python\iree\runtime\_binding.py", line 17, in <module>
    from iree import _runtime
ImportError: cannot import name '_runtime' from 'iree' (unknown location)
```

**Comment by nirvedhmeshram** [comment]
This was a python version issue, I use 3.11 but it was finding 3.10, I believe the reason was 3.11 did not have numpy installed so after forcing -DPython3_EXECUTABLE that issue was revealed, then after installing it, its working alright.
