### ISSUE TITLE
Improve handling of 'torch' input type

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#15353]
Spotted this while responding to https://github.com/nod-ai/SHARK-Turbine/issues/118#issuecomment-1787497716

I'm trying to compile a sample program exported by SHARK-Turbine using [this Colab notebook](https://colab.research.google.com/github/openxla/iree/blob/main/samples/colab/pytorch_aot_simple.ipynb). Some workflows that should work do not.
<details><summary>Click to expand sample MLIR</summary>
<p>

```mlir
module @LinearModule {
  util.global private @_params.weight {noinline} = dense<[[1.54099607, -0.293428898, -2.17878938], [0.568431258, -1.08452237, -1.39859545], [0.403346837, 0.838026344, -0.719257593], [-0.403343529, -0.596635341, 0.182036489]]> : tensor<4x3xf32>
  util.global private @_params.bias {noinline} = dense<[-0.856674611, 1.10060418, -1.07118738]> : tensor<3xf32>
  func.func @main(%arg0: tensor<4xf32>) -> tensor<3xf32> attributes {torch.args_schema = "[1, {\22type\22: \22builtins.tuple\22, \22context\22: \22null\22, \22children_spec\22: [{\22type\22: \22builtins.list\22, \22context\22: \22null\22, \22children_spec\22: [{\22type\22: null, \22context\22: null, \22children_spec\22: []}]}, {\22type\22: \22builtins.dict\22, \22context\22: \22[]\22, \22children_spec\22: []}]}]", torch.return_schema = "[1, {\22type\22: null, \22context\22: null, \22children_spec\22: []}]"} {
    %0 = torch_c.from_builtin_tensor %arg0 : tensor<4xf32> -> !torch.vtensor<[4],f32>
    %1 = call @forward(%0) : (!torch.vtensor<[4],f32>) -> !torch.vtensor<[3],f32>
    %2 = torch_c.to_builtin_tensor %1 : !torch.vtensor<[3],f32> -> tensor<3xf32>
    return %2 : tensor<3xf32>
  }
  func.func private @forward(%arg0: !torch.vtensor<[4],f32>) -> !torch.vtensor<[3],f32> {
    %int0 = torch.constant.int 0
    %0 = torch.aten.unsqueeze %arg0, %int0 : !torch.vtensor<[4],f32>, !torch.int -> !torch.vtensor<[1,4],f32>
    %_params.weight = util.global.load @_params.weight : tensor<4x3xf32>
    %1 = torch_c.from_builtin_tensor %_params.weight : tensor<4x3xf32> -> !torch.vtensor<[4,3],f32>
    %2 = torch.aten.mm %0, %1 : !torch.vtensor<[1,4],f32>, !torch.vtensor<[4,3],f32> -> !torch.vtensor<[1,3],f32>
    %int0_0 = torch.constant.int 0
    %3 = torch.aten.squeeze.dim %2, %int0_0 : !torch.vtensor<[1,3],f32>, !torch.int -> !torch.vtensor<[3],f32>
    %_params.bias = util.global.load @_params.bias : tensor<3xf32>
    %4 = torch_c.from_builtin_tensor %_params.bias : tensor<3xf32> -> !torch.vtensor<[3],f32>
    %int1 = torch.constant.int 1
    %5 = torch.aten.add.Tensor %3, %4, %int1 : !torch.vtensor<[3],f32>, !torch.vtensor<[3],f32>, !torch.int -> !torch.vtensor<[3],f32>
    return %5 : !torch.vtensor<[3],f32>
  }
}
```

</p>
</details> 

## Compilation workflows tested

* CLI `iree-compile` with `--iree-input-type=torch` works:
  ```
  D:\dev\projects\iree-build
  λ .\tools\iree-compile.exe D:\dev\scratch\iree-tmp\python\torch_input.mlir --iree-input-type=torch --iree-hal-target-backends=llvm-cpu -o D:\dev\scratch\iree-tmp\python\torch_output.vmfb
  ```
  
* CLI `iree-compile` _without_ `iree-input-type=torch` does not work:
  ```
  D:\dev\projects\iree-build
  λ .\tools\iree-compile.exe D:\dev\scratch\iree-tmp\python\torch_input.mlir --iree-hal-target-backends=llvm-cpu -o D:\dev\scratch\iree-tmp\python\torch_output.vmfb
  D:\dev\scratch\iree-tmp\python\torch_input.mlir:5:10: error: failed to legalize operation 'torch_c.from_builtin_tensor' that was explicitly marked illegal
      %0 = torch_c.from_builtin_tensor %arg0 : tensor<4xf32> -> !torch.vtensor<[4],f32>
           ^
  D:\dev\scratch\iree-tmp\python\torch_input.mlir:4:3: note: called from
    func.func @main(%arg0: tensor<4xf32>) -> tensor<3xf32> attributes {torch.args_schema = "[1, {\22type\22: \22builtins.tuple\22, \22context\22: \22null\22, \22children_spec\22: [{\22type\22: \22builtins.list\22, \22context\22: \22null\22, \22children_spec\22: [{\22type\22: null, \22context\22: null, \22children_spec\22: []}]}, {\22type\22: \22builtins.dict\22, \22context\22: \22[]\22, \22children_spec\22: []}]}]", torch.return_schema = "[1, {\22type\22: null, \22context\22: null, \22children_spec\22: []}]"} {
    ^
  D:\dev\scratch\iree-tmp\python\torch_input.mlir:5:10: note: see current operation: %25 = "torch_c.from_builtin_tensor"(%24) : (tensor<4xf32>) -> !torch.vtensor<[4],f32>
      %0 = torch_c.from_builtin_tensor %arg0 : tensor<4xf32> -> !torch.vtensor<[4],f32>
           ^
  ```

* Python `iree.compiler.tools.compile_file` with `input_type="torch"` does not work:

  ```python
  import iree.compiler.tools
  
  binary = iree.compiler.tools.compile_file(
      "D:/dev/scratch/iree-tmp/python/torch_input.mlir",
      input_type="torch",
      target_backends=["llvm-cpu"],
  )
  ```
  
  ```
  D:\dev\projects\iree-build
  λ python3 D:\dev\scratch\iree-tmp\python\torch_input.py
  Traceback (most recent call last):
    File "D:\dev\scratch\iree-tmp\python\torch_input.py", line 36, in <module>
      binary = iree.compiler.tools.compile_file(
    File "D:\dev\projects\iree-build\compiler\bindings\python\iree\compiler\tools\core.py", line 240, in compile_file
      options = CompilerOptions(**kwargs)
    File "<string>", line 17, in __init__
    File "D:\dev\projects\iree-build\compiler\bindings\python\iree\compiler\tools\core.py", line 161, in __post_init__
      self.input_type = InputType.parse(self.input_type)
    File "D:\dev\projects\iree-build\compiler\bindings\python\iree\compiler\tools\core.py", line 65, in parse
      raise ValueError(
  ValueError: For input_type= argument, expected one of: NONE, AUTO, STABLEHLO, STABLEHLO_XLA, TOSA, TM_TENSOR
  ```

* Python `iree.compiler.tools.compile_file` without `input_type="torch"` does not work:

  ```python
  import iree.compiler.tools
  
  binary = iree.compiler.tools.compile_file(
      "D:/dev/scratch/iree-tmp/python/torch_input.mlir", target_backends=["llvm-cpu"]
  )
  ```
  
  ```
  D:\dev\projects\iree-build
  λ python3 D:\dev\scratch\iree-tmp\python\torch_input.py
  Traceback (most recent call last):
    File "D:\dev\scratch\iree-tmp\python\torch_input.py", line 9, in <module>
      binary = iree.compiler.tools.compile_file(
    File "D:\dev\projects\iree-build\compiler\bindings\python\iree\compiler\tools\core.py", line 254, in compile_file
      result = invoke_immediate(cl)
    File "D:\dev\projects\iree-build\compiler\bindings\python\iree\compiler\tools\binaries.py", line 198, in invoke_immediate
      raise CompilerToolError(process)
  iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile.exe
  Error code: 1
  Diagnostics:
  D:/dev/scratch/iree-tmp/python/torch_input.mlir:5:10: error: failed to legalize operation 'torch_c.from_builtin_tensor' that was explicitly marked illegal
      %0 = torch_c.from_builtin_tensor %arg0 : tensor<4xf32> -> !torch.vtensor<[4],f32>
           ^
  D:/dev/scratch/iree-tmp/python/torch_input.mlir:4:3: note: called from
    func.func @main(%arg0: tensor<4xf32>) -> tensor<3xf32> attributes {torch.args_schema = "[1, {\22type\22: \22builtins.tuple\22, \22context\22: \22null\22, \22children_spec\22: [{\22type\22: \22builtins.list\22, \22context\22: \22null\22, \22children_spec\22: [{\22type\22: null, \22context\22: null, \22children_spec\22: []}]}, {\22type\22: \22builtins.dict\22, \22context\22: \22[]\22, \22children_spec\22: []}]}]", torch.return_schema = "[1, {\22type\22: null, \22context\22: null, \22children_spec\22: []}]"} {
    ^
  
  
  Invoked with:
   iree-compile.exe D:\dev\projects\iree-build\compiler\bindings\python\iree\compiler\tools\..\_mlir_libs\iree-compile.exe D:/dev/scratch/iree-tmp/python/torch_input.mlir --iree-input-type=auto --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=llvm-cpu --iree-llvmcpu-embedded-linker-path=D:\dev\projects\iree-build\compiler\bindings\python\iree\compiler\tools\..\_mlir_libs\iree-lld.exe --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
  
  Need more information? Set IREE_SAVE_TEMPS=/some/dir in your environment to save all artifacts and reproducers.
  ```

## How to fix

All four should work. Probably needs changes across [`compiler/bindings/python/iree/compiler/tools/core.py`](https://github.com/openxla/iree/blob/main/compiler/bindings/python/iree/compiler/tools/core.py) and the input pipeline C++ code.

We should also have unit tests for each of these workflows.

**Comment by ScottTodd** [comment]
Handling 'torch' in [`InputConversion/Common/AutoInputConversionPipeline.cpp`](https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/InputConversion/Common/AutoInputConversionPipeline.cpp) may be tricky, since StableHLO and TOSA are "built in to the compiler directly" while Torch is implemented as a compiler plugin ([`compiler/plugins/input/Torch/torch-iree`](https://github.com/openxla/iree/tree/main/compiler/plugins/input/Torch/torch-iree)). Still reading through code, but it feels like we could

1. Add hooks on compiler plugins for plugging in to auto input conversion (if not already there)
2. (follow-up) Convert StableHLO and TOSA input support into compiler plugins themselves
