### ISSUE TITLE
Converting from kaggle google/aiy/tfLite/vision-classifier-birds-v1 fails

### ISSUE THREAD

**Issue by Ughuuu** [iree-org/iree#18209]
### What happened?

Converting the model `google/aiy/tfLite/vision-classifier-birds-v1` from **kaggle** with version `20240812.983` fails. https://github.com/iree-gd/iree.zoo/actions/runs/10377043813/job/28730530553. Logs here:
```
Traceback (most recent call last):
  File "/home/runner/work/iree.zoo/iree.zoo/convert_tflite.py", line 70, in <module>
    iree_tflite_compile.compile_file(
  File "/home/runner/.local/lib/python3.10/site-packages/iree/compiler/tools/tflite.py", line 119, in compile_file
    result = invoke_pipeline([compile_cl])
  File "/home/runner/.local/lib/python3.10/site-packages/iree/compiler/tools/binaries.py", line 261, in invoke_pipeline
    raise CompilerToolError(stage.completed)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile
Error code: 1
Diagnostics:
failed to translate executables
<unknown>:0: error: failed to legalize operation 'arith.constant'
<unknown>:0: error: loc(callsite("module/MobilenetV2/expanded_conv_1/expand/Relu6" at "main")): failed to run translation of source executable to target executable for backend #hal.executable.target<"metal-spirv", "metal-msl-fb", {iree.gpu.target = #iree_gpu.target<arch = "apple", features = "spirv:v1.3,cap:Shader", wgp = <compute =  fp32|fp16|int64|int32|int16|int8, storage =  b64|b32|b16|b8, subgroup =  shuffle|arithmetic, dot =  dp4xi8toi32, mma = [], subgroup_size_choices = [32], max_workgroup_sizes = [1024, 1024, 1024], max_thread_count_per_workgroup = 1024, max_workgroup_memory_bytes = 32768>>}>
<unknown>:0: note: loc("main"): called from


Invoked with:
 iree-compile /home/runner/.local/lib/python3.10/site-packages/iree/compiler/tools/../_mlir_libs/iree-compile /tmp/tmp19y8svfr/tfl-iree-input.mlir --iree-input-type=tosa --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=metal-spirv -o=build/iree.metal-spirv.vmfb --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
```

### Steps to reproduce your issue

1. Download the model from kaggle
2. Convert it using iree compiler
3. See error

Also if you want you can fork the repo https://github.com/iree-gd/iree.zoo and run convert action from there to see the logs

### What component(s) does this issue relate to?

Compiler

### Version information

20240812.983

**Comment by Ughuuu** [comment]
Closing in favour of https://github.com/iree-org/iree/issues/18210
