### ISSUE TITLE
MMAIntrinsicAttr used incorrectly causing compiler crash

### ISSUE THREAD

**Issue by KyleHerndon** [iree-org/iree#19021]
### What happened?

When I try to compile a 405b sharded llama3.1 fp16 mlir generated from SHARK-Platform, I get the following error:
```
LLVM ERROR: can't create Attribute 'mlir::iree_compiler::IREE::GPU::MMAIntrinsicAttr' because storage uniquer isn't initialized: the dialect was likely not loaded, or the attribute wasn't added with addAttributes<...>() in the Dialect::initialize() method.
Please report issues to https://github.com/iree-org/iree/issues and include the crash backtrace.
Stack dump:
0.      Program arguments: ../iree-build/tools/iree-compile ./405b_f16_tp8.vm.mlir --iree-hal-target-device=hip[0] --iree-hal-target-device=hip[1] --iree-hal-target-device=hip[2] --iree-hal-target-device=hip[3] --iree-hal-target-device=hip[4] --iree-hal-target-device=hip[5] --iree-hal-target-device=hip[6] --iree-hal-target-device=hip[7] --iree-hal-executable-debug-level=3 --iree-hip-target=gfx942 --iree-hal-force-indirect-command-buffers=true --iree-stream-resource-memory-model=discrete --iree-hip-legacy-sync=false -o 405b_f16_tp8.vmfb --compile-from=vm
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  libIREECompiler.so 0x000070f214272447 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 39
1  libIREECompiler.so 0x000070f214270680 llvm::sys::RunSignalHandlers() + 80
2  libIREECompiler.so 0x000070f214272b0a
3  libc.so.6          0x000070f20d042520
4  libc.so.6          0x000070f20d0969fc pthread_kill + 300
5  libc.so.6          0x000070f20d042476 raise + 22
6  libc.so.6          0x000070f20d0287f3 abort + 211
7  libIREECompiler.so 0x000070f2141f1153 llvm::report_fatal_error(llvm::Twine const&, bool) + 419
8  libIREECompiler.so 0x000070f214410210
9  libIREECompiler.so 0x000070f2143fd190
10 libIREECompiler.so 0x000070f216e23990
11 libIREECompiler.so 0x000070f216e241a5
12 libIREECompiler.so 0x000070f21585aa8b
13 libIREECompiler.so 0x000070f21585882b
14 libIREECompiler.so 0x000070f2158585f5
15 libIREECompiler.so 0x000070f215b18a4e
16 libIREECompiler.so 0x000070f215b1859b
17 libIREECompiler.so 0x000070f214461ee5 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) + 629
18 libIREECompiler.so 0x000070f214462658 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) + 328
19 libIREECompiler.so 0x000070f2144649a9 mlir::PassManager::run(mlir::Operation*) + 969
20 libIREECompiler.so 0x000070f2141c4b60 ireeCompilerInvocationPipeline + 3424
21 libIREECompiler.so 0x000070f2143edfc8
22 libIREECompiler.so 0x000070f2143ed801
23 libc.so.6          0x000070f20d029d90
24 libc.so.6          0x000070f20d029e40 __libc_start_main + 128
25 iree-compile       0x00005ad94a9f06c5
```

### Steps to reproduce your issue

Using the following compilation command:
```
../iree-build/tools/iree-compile ./405b_f16_tp8.vm.mlir   --iree-hal-target-device=hip[0] --iree-hal-target-device=hip[1] --iree-hal-target-device=hip[2] --iree-hal-target-device=hip[3] --iree-hal-target-device=hip[4] --iree-hal-target-device=hip[5] --iree-hal-target-device=hip[6] --iree-hal-target-device=hip[7]   --iree-hal-executable-debug-level=3 --iree-hip-target=gfx942 --iree-hal-force-indirect-command-buffers=true --iree-stream-resource-memory-model=discrete --iree-hip-legacy-sync=false   -o 405b_f16_tp8.vmfb --compile-from=vm
```

### What component(s) does this issue relate to?

Compiler

### Version information

`2f15eeba3ddbcf75b3c459dce6dc19ee30f86537`

### Additional context

[Original MLIR](https://sharkpublic.blob.core.windows.net/sharkpublic/kyle/llama3.1_405b_fp16_nondecomopsed_tp8_bs4.mlir)
[Input](https://sharkpublic.blob.core.windows.net/sharkpublic/kyle/405b_f16_tp8.input.mlir)
[Flow](https://sharkpublic.blob.core.windows.net/sharkpublic/kyle/405b_f16_tp8.flow.mlir)
[Stream](https://sharkpublic.blob.core.windows.net/sharkpublic/kyle/405b_f16_tp8.stream.mlir)
[VM](https://sharkpublic.blob.core.windows.net/sharkpublic/kyle/405b_f16_tp8.vm.mlir)

**Comment by kuhar** [comment]
@bjacob or @Groverkss would you be able to look at this?

**Comment by bjacob** [comment]
I can, (EDIT - saw the reproducer in the issue description).

**Comment by bjacob** [comment]
```
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140736845930496) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140736845930496) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140736845930496, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007fffd9b9c476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007fffd9b827f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007fffdead4e24 in llvm::report_fatal_error (Reason=..., GenCrashDiag=true) at /home/benjacob/iree/third_party/llvm-project/llvm/lib/Support/ErrorHandling.cpp:124
#6  0x00007fffdeff81c1 in mlir::detail::AttributeUniquer::getWithTypeID<mlir::iree_compiler::IREE::GPU::MMAIntrinsicAttr, mlir::iree_compiler::IREE::GPU::MMAIntrinsic> (ctx=0x555555610570, typeID=..., 
    args=@0x7fffffff9e7c: mlir::iree_compiler::IREE::GPU::MMAIntrinsic::MFMA_F32_16x16x4_F32) at /home/benjacob/iree/third_party/llvm-project/mlir/include/mlir/IR/AttributeSupport.h:233
#7  0x00007fffdeff80ea in mlir::detail::AttributeUniquer::get<mlir::iree_compiler::IREE::GPU::MMAIntrinsicAttr, mlir::iree_compiler::IREE::GPU::MMAIntrinsic> (ctx=0x555555610570, 
    args=@0x7fffffff9e7c: mlir::iree_compiler::IREE::GPU::MMAIntrinsic::MFMA_F32_16x16x4_F32) at /home/benjacob/iree/third_party/llvm-project/mlir/include/mlir/IR/AttributeSupport.h:220
#8  0x00007fffdefcca7f in mlir::detail::StorageUserBase<mlir::iree_compiler::IREE::GPU::MMAIntrinsicAttr, mlir::Attribute, mlir::iree_compiler::IREE::GPU::detail::MMAIntrinsicAttrStorage, mlir::detail::AttributeUniquer>::get<mlir::iree_compiler::IREE::GPU::MMAIntrinsic> (ctx=0x555555610570, args=@0x7fffffff9e7c: mlir::iree_compiler::IREE::GPU::MMAIntrinsic::MFMA_F32_16x16x4_F32) at /home/benjacob/iree/third_party/llvm-project/mlir/include/mlir/IR/StorageUniquerSupport.h:181
#9  0x00007fffdefaac1c in mlir::iree_compiler::IREE::GPU::MMAIntrinsicAttr::get (context=0x555555610570, value=mlir::iree_compiler::IREE::GPU::MMAIntrinsic::MFMA_F32_16x16x4_F32)
    at compiler/src/iree/compiler/Codegen/Dialect/GPU/IR/IREEGPUAttrs.cpp.inc:725
#10 0x00007fffdefb43d3 in mlir::iree_compiler::IREE::GPU::MMAAttr::get (context=0x555555610570, type=mlir::iree_compiler::IREE::GPU::MMAIntrinsic::MFMA_F32_16x16x4_F32)
    at /home/benjacob/iree/compiler/src/iree/compiler/Codegen/Dialect/GPU/IR/IREEGPUAttrs.cpp:378
#11 0x00007fffe4ee72fe in mlir::iree_compiler::IREE::GPU::(anonymous namespace)::createTargetAttr (details=..., arch=..., features=..., context=0x555555610570)
    at /home/benjacob/iree/compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/KnownTargets.cpp:95
#12 0x00007fffe4ee86a1 in mlir::iree_compiler::IREE::GPU::getHIPTargetDetails (target=..., features=..., context=0x555555610570) at /home/benjacob/iree/compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/KnownTargets.cpp:657
#13 0x00007fffe1db254a in mlir::iree_compiler::IREE::HAL::ROCMTargetBackend::getExecutableTarget (this=0x555562e4a8f0, deviceID=..., context=0x555555610570) at /home/benjacob/iree/compiler/plugins/target/ROCM/ROCMTarget.cpp:246
#14 0x00007fffe1db03e5 in mlir::iree_compiler::IREE::HAL::ROCMTargetBackend::getDefaultExecutableTargets (this=0x555562e4a8f0, context=0x555555610570, deviceID=..., deviceConfigAttr=..., executableTargetAttrs=...)
    at /home/benjacob/iree/compiler/plugins/target/ROCM/ROCMTarget.cpp:221
#15 0x00007fffe1dafaee in mlir::iree_compiler::IREE::HAL::HIPTargetDevice::getDefaultDeviceTarget (this=0x555563a11d50, context=0x555555610570, targetRegistry=...) at /home/benjacob/iree/compiler/plugins/target/ROCM/ROCMTarget.cpp:851
#16 0x00007fffe239f889 in mlir::iree_compiler::IREE::HAL::(anonymous namespace)::resolveAliasAttr (forOp=0x5555630f6d40, aliasAttr=..., targetRegistry=...)
    at /home/benjacob/iree/compiler/src/iree/compiler/Dialect/HAL/Transforms/ResolveDeviceAliases.cpp:50
#17 0x00007fffe239f3e3 in mlir::iree_compiler::IREE::HAL::(anonymous namespace)::resolveNestedAliasAttrs (forOp=0x5555630f6d40, attr=..., targetRegistry=...)
    at /home/benjacob/iree/compiler/src/iree/compiler/Dialect/HAL/Transforms/ResolveDeviceAliases.cpp:85
#18 0x00007fffe239f193 in mlir::iree_compiler::IREE::HAL::(anonymous namespace)::ResolveDeviceAliasesPass::runOnOperation (this=0x55555aa10820)
    at /home/benjacob/iree/compiler/src/iree/compiler/Dialect/HAL/Transforms/ResolveDeviceAliases.cpp:122
#19 0x00007fffdf0ce75b in mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int)::$_7::operator()() const (this=0x7fffffffae88)
    at /home/benjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:526
#20 0x00007fffdf0ce6f5 in llvm::function_ref<void ()>::callback_fn<mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int)::$_7>(long) (callable=140737488334472)
    at /home/benjacob/iree/third_party/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:45
#21 0x00007fffdeaae559 in llvm::function_ref<void ()>::operator()() const (this=0x7fffffffae10) at /home/benjacob/iree/third_party/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:68
#22 0x00007fffdf0d18dd in mlir::MLIRContext::executeAction<mlir::PassExecutionAction, mlir::Pass&>(llvm::function_ref<void ()>, llvm::ArrayRef<mlir::IRUnit>, mlir::Pass&) (this=0x555555610570, actionFn=..., irUnits=..., args=...)
    at /home/benjacob/iree/third_party/llvm-project/mlir/include/mlir/IR/MLIRContext.h:280
#23 0x00007fffdf0c9c6a in mlir::detail::OpToOpPassAdaptor::run (pass=0x55555aa10820, op=0x5555628268e0, am=..., verifyPasses=true, parentInitGeneration=1) at /home/benjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:520
#24 0x00007fffdf0ca224 in mlir::detail::OpToOpPassAdaptor::runPipeline (pm=..., op=0x5555628268e0, am=..., verifyPasses=true, parentInitGeneration=1, instrumentor=0x0, parentInfo=0x0)
    at /home/benjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:592
#25 0x00007fffdf0cbd0c in mlir::PassManager::runPasses (this=0x55555567b800, op=0x5555628268e0, am=...) at /home/benjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:905
#26 0x00007fffdf0cbc2f in mlir::PassManager::run (this=0x55555567b800, op=0x5555628268e0) at /home/benjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:885
#27 0x00007fffde9e91ea in mlir::iree_compiler::embed::(anonymous namespace)::Invocation::runPipeline (this=0x555555665ba0, pipeline=IREE_COMPILER_PIPELINE_STD)
    at /home/benjacob/iree/compiler/src/iree/compiler/API/Internal/CompilerDriver.cpp:1008
#28 0x00007fffde9e8ac3 in ireeCompilerInvocationPipeline (inv=0x555555665ba0, pipeline=IREE_COMPILER_PIPELINE_STD) at /home/benjacob/iree/compiler/src/iree/compiler/API/Internal/CompilerDriver.cpp:1447
#29 0x00007fffdef9bd5e in mlir::iree_compiler::runIreecMain(int, char**)::$_2::operator()(iree_compiler_source_t*) const (this=0x7fffffffc298, source=0x5555556658e0)
    at /home/benjacob/iree/compiler/src/iree/compiler/Tools/iree_compile_lib.cc:254
#30 0x00007fffdef9b18e in mlir::iree_compiler::runIreecMain (argc=18, argv=0x7fffffffdd88) at /home/benjacob/iree/compiler/src/iree/compiler/Tools/iree_compile_lib.cc:355
#31 0x00007fffdea3dfab in ireeCompilerRunMain (argc=18, argv=0x7fffffffdd88) at /home/benjacob/iree/compiler/src/iree/compiler/API/Internal/IREECompileToolEntryPoint.cpp:12
#32 0x0000555555555162 in main (argc=18, argv=0x7fffffffdd88) at /home/benjacob/iree/tools/iree-compile-main.cc:9
```

**Comment by bjacob** [comment]
Fix coming: https://github.com/iree-org/iree/pull/19043
