### ISSUE TITLE
[Python Bindings] Conflict between Linalg and IREEGPU iterator types in python bindings

### ISSUE THREAD

**Issue by Max191** [iree-org/iree#19269]
Several parts of IREEGPU dialect were recently exposed in the python bindings, and there is now a conflict in the registration the IteratorTypes:

Repro steps:
```
python -m pip install \
  --find-links https://iree.dev/pip-release-links.html \
  --upgrade \
  --pre \
  iree-base-compiler \
  iree-base-runtime

python
>>> from iree.compiler.dialects import linalg
>>> from iree.compiler.dialects import iree_gpu
```
 Resulting faliure:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mdawkins/shark-ai/tuner/.venv/lib/python3.11/site-packages/iree/compiler/dialects/iree_gpu.py", line 8, in <module>
    from ._iree_gpu_enum_gen import *
  File "/home/mdawkins/shark-ai/tuner/.venv/lib/python3.11/site-packages/iree/compiler/dialects/_iree_gpu_enum_gen.py", line 362, in <module>
    @register_attribute_builder("IteratorType")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mdawkins/shark-ai/tuner/.venv/lib/python3.11/site-packages/iree/compiler/ir.py", line 14, in decorator_builder
    AttrBuilder.insert(kind, func, replace=replace)
RuntimeError: Attribute builder for 'IteratorType' is already registered with func: <function _iteratortype at 0x7f4f678cc5e0>
```

I believe this is because iree_gpu has defined its own version of iterator types, which has the same name as the iterator types in linalg.

**Comment by ANTIAN-STAR** [comment]
The error you're encountering arises from a conflict in the registration of the IteratorType attribute between two dialects: linalg and iree_gpu. Both dialects are trying to register an attribute named IteratorType, but only one registration can occur, leading to a RuntimeError when the second one attempts to register the same name.

Possible Causes:
Multiple Definitions: The IteratorType is defined in both linalg and iree_gpu dialects. This causes the conflict because both dialects are trying to register an attribute with the same name.
IREE's Namespace Conflict: Since both linalg and iree_gpu share common functionality (like iterator types), there can be conflicts if they try to register similar or identical names.
Potential Solutions:
Isolate Dialect Registrations:

One quick solution could be to explicitly ensure that the registrations for IteratorType happen in isolation, depending on which dialect you are using. You can try to import the dialects sequentially or conditionally to avoid simultaneous conflicting registrations.
Modify the iree_gpu Registration:

If you have control over the code, you can modify the iree_gpu dialect to register the IteratorType attribute under a different name to avoid conflicts with linalg.
Conditional Import:

Since the issue arises from the simultaneous import of both linalg and iree_gpu, you can try importing them conditionally or after checking if one has already been imported:
from iree.compiler.dialects import linalg
try:
    from iree.compiler.dialects import iree_gpu
except RuntimeError:
    print("IREE GPU dialect registration failed due to conflict")
Temporary Workaround - Use One Dialect:

If possible, limit your usage to one dialect at a time. If you are not specifically dependent on both dialects simultaneously, you can try isolating them:
from iree.compiler.dialects import linalg
# Use linalg functionality
Or:

from iree.compiler.dialects import iree_gpu
# Use iree_gpu functionality
File a Bug or Check Existing Issues:

Since this issue might be related to recent changes in the IREE bindings, it could be a known bug that has not yet been fixed. Check the [IREE GitHub issues](https://github.com/llvm/iree/issues) or file a bug report to let the developers know about this conflict. They might offer a more permanent solution, or it might already be fixed in a newer release.
Update IREE or Dialects:

Make sure you have the latest versions of the iree-base-compiler and iree-base-runtime packages. Sometimes, these kinds of issues are resolved in minor updates or patches.
Additional Debugging:
If none of the above solutions work, you may want to dive deeper into the registration process to see if there is a way to check whether IteratorType is already registered before attempting to register it again. This would require modifying the IREE source code or contributing a patch.

Let me know if you'd like more detailed help with debugging or modifying the source!

**Comment by krzysz00** [comment]
I'm going to perform necromancy and note that I'm hitting this today on what I expected to be a clean rebuild of IREE

**Comment by kuhar** [comment]
@RattataKing

**Comment by RattataKing** [comment]
We can use monkey patching to work around with the issue, see this example: https://github.com/nod-ai/amd-shark-ai/blob/94f30420a5d20d53230f545f4f257020b261a63e/amdsharktuner/amdsharktuner/__init__.py#L10-L17

Now we have the upstream fix here: https://github.com/llvm/llvm-project/pull/187191, new IREE build should no longer have this issue.
