### ISSUE TITLE
Missing legalization for `mhlo.round_nearest_afz`

### ISSUE THREAD

**Issue by hawkinsp** [iree-org/iree#7618]
Repro:
```
from iree.compiler import compile_str

CODE = """
module  {
  func @main(%arg0: tensor<1x4xf32>) -> tensor<1x4xf32> {
    %0 = "mhlo.round_nearest_afz"(%arg0) : (tensor<1x4xf32>) -> tensor<1x4xf32>
    return %0 : tensor<1x4xf32>
  }
}"""

compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
```

Get:
```
$ python t.py
Traceback (most recent call last):
  File "t.py", line 11, in <module>
    compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/core.py", line 262, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/binaries.py", line 201, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool ireec
Diagnostics:
<stdin>:4:10: error: failed to legalize operation 'mhlo.round_nearest_afz' that was explicitly marked illegal
    %0 = "mhlo.round_nearest_afz"(%arg0) : (tensor<1x4xf32>) -> tensor<1x4xf32>
         ^
<stdin>:3:3: note: called from
  func @main(%arg0: tensor<1x4xf32>) -> tensor<1x4xf32> {
  ^
<stdin>:2:1: error: conversion from source -> vm failed
module  {
^


Invoked with:
 ireec /usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/ireec - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
```

**Comment by rsuderman** [comment]
Fix was upstreamed and was locally validated.

**Comment by ScottTodd** [comment]
> Fix was upstreamed and was locally validated.

These tests are still disabled: https://github.com/google/iree/blob/e9c786761f91f02e854875ca5b8b257cc706a993/iree/test/e2e/xla_ops/round.mlir#L1-L6

https://github.com/google/iree/blob/e9c786761f91f02e854875ca5b8b257cc706a993/iree/test/e2e/xla_ops/BUILD#L84-L86

and I get compile errors trying to enable them:
```
[build] FAILED: iree/test/e2e/xla_ops/check_vmvx_vmvx_round.mlir_module.vmfb D:/dev/projects/iree-build/iree/test/e2e/xla_ops/check_vmvx_vmvx_round.mlir_module.vmfb 
[build] cmd.exe /C "cd /D D:\dev\projects\iree-build\iree\test\e2e\xla_ops && D:\dev\projects\iree-build\iree\tools\iree-translate.exe -iree-mlir-to-vm-bytecode-module -mlir-print-op-on-diagnostic=false --iree-hal-target-backends=vmvx -iree-input-type=mhlo D:/dev/projects/iree/iree/test/e2e/xla_ops/round.mlir -o check_vmvx_vmvx_round.mlir_module.vmfb -iree-llvm-embedded-linker-path=\"D:/dev/projects/iree-build/third_party/llvm-project/llvm/bin/lld.exe\""
[build] D:/dev/projects/iree/iree/test/e2e/xla_ops/round.mlir:3:13: error: failed to legalize operation 'math.copysign' that was explicitly marked illegal
[build]   %result = "mhlo.round_nearest_afz"(%input) : (tensor<7xf32>) -> tensor<7xf32>
[build]             ^
```

What fix was upstreamed? Should we update our tests to use a different op?

**Comment by ScottTodd** [comment]
Or maybe `mhlo.round_nearest_afz` now lowers further, but we also need `math.copysign` to support the op end to end?

**Comment by ScottTodd** [comment]
Tested how `math.copysign` is handled a bit more

backend | result
-- | --
llvm CPU | lowers successfully
llvm WebAssembly | same error as on https://github.com/google/iree/issues/8514
CUDA | success, `ConvertToNVVM` lowers to `llvm.intr.copysign`
SPIR-V | missing lowering in `ConvertToSPIRV`
VMVX | missing lowering in `IREE::VM::ConversionPass`

**Comment by rsuderman** [comment]
`mhlo-to-linalg` was changed to lower to `math.round`. This works for `llvm.round` however `glsl.round` does not guarantee rounding away-from-zero.

**Comment by antiagainst** [comment]
Yeah. GLSL's round is fuzzy on how to handle the 0.5 situation; we'd need to emit additional ops to check and handle that case by ourselves.

**Comment by antiagainst** [comment]
Related: https://github.com/iree-org/iree/issues/9617
