### ISSUE TITLE
"Failed to legalize operation 'mhlo.complex' marked as erased"

### ISSUE THREAD

**Issue by hawkinsp** [iree-org/iree#7623]
Repro:
```
from iree.compiler import compile_str

CODE = """
module  {
  func @main(%arg0: tensor<3x4xf32>, %arg1: tensor<3x1xf32>) -> tensor<3x4xcomplex<f32>> {
    %0 = "mhlo.broadcast_in_dim"(%arg1) {broadcast_dimensions = dense<[0, 1]> : tensor<2xi64>} : (tensor<3x1xf32>) -> tensor<3x4xf32>
    %1 = mhlo.complex(%arg0, %0) : (tensor<3x4xf32>, tensor<3x4xf32>) -> tensor<3x4xcomplex<f32>>
    return %1 : tensor<3x4xcomplex<f32>>
  }
}
"""

compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
```

Get:
```
$ python t.py
Traceback (most recent call last):
  File "t.py", line 13, in <module>
    compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/core.py", line 262, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/binaries.py", line 201, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool ireec
Diagnostics:
<stdin>:5:10: error: failed to legalize operation 'mhlo.complex' marked as erased
    %1 = mhlo.complex(%arg0, %0) : (tensor<3x4xf32>, tensor<3x4xf32>) -> tensor<3x4xcomplex<f32>>
         ^
<stdin>:3:3: note: called from
  func @main(%arg0: tensor<3x4xf32>, %arg1: tensor<3x1xf32>) -> tensor<3x4xcomplex<f32>> {
  ^
<stdin>:3:3: note: found live user of result #0: %6 = hal.tensor.cast %5 : tensor<3x4xcomplex<f32>> -> !hal.buffer_view loc("<stdin>":3:3)
<stdin>:2:1: error: conversion from source -> vm failed
module  {
^


Invoked with:
 ireec /usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/ireec - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
```

**Comment by sv-intel** [comment]
Hello,

I am also interesting in resolution of the issue. Is there any plans or ideas how to solve it?

**Comment by jpienaar** [comment]
Still fails, reduced test case for failure:

```mlir
func.func @main(%arg0: tensor<3x4xf32> loc("/tmp/7623.mlir":2:19), %arg1: tensor<3x1xf32> loc("/tmp/7623.mlir":2:43)) -> tensor<3x4xcomplex<f32>> {
  %0 = "mhlo.broadcast_in_dim"(%arg1) {broadcast_dimensions = dense<[0, 1]> : tensor<2xi64>} : (tensor<3x1xf32>) -> tensor<3x4xf32> loc("/tmp/7623.mlir":3:10)
  %1 = mhlo.complex(%arg0, %0) : (tensor<3x4xf32>, tensor<3x4xf32>) -> tensor<3x4xcomplex<f32>> loc("/tmp/7623.mlir":4:10)
  return %1 : tensor<3x4xcomplex<f32>> loc("/tmp/7623.mlir":5:5)
} loc("/tmp/7623.mlir":2:3)
```

```sh
./tools/iree-opt  --iree-mhlo-to-linalg-on-tensors /tmp/7623.mlir --debug
```

with result

```
Legalizing operation : 'mhlo.complex'(0x7536f80) {
  %3 = "mhlo.complex"(%arg0, %2) : (tensor<3x4xf32>, tensor<3x4xf32>) -> tensor<3x4xcomplex<f32>>

  * Fold {
  } -> FAILURE : unable to fold

  * Pattern : 'mhlo.complex -> ()' {
Trying to match "mlir::iree_compiler::MHLO::(anonymous namespace)::ElideComplexPattern"
    ** Erase   : 'mhlo.complex'(0x7536f80)
"mlir::iree_compiler::MHLO::(anonymous namespace)::ElideComplexPattern" result 1
  } -> SUCCESS : pattern applied successfully
// *** IR Dump After Pattern Application ***
mlir-asm-printer: Verifying operation: func.func
func.func @main(%arg0: tensor<3x4xf32>, %arg1: tensor<3x1xf32>) -> tensor<3x4xcomplex<f32>> {
  %0 = linalg.init_tensor [3, 4] : tensor<3x4xf32>
  %1 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, 0)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%arg1 : tensor<3x1xf32>) outs(%0 : tensor<3x4xf32>) {
  ^bb0(%arg2: f32, %arg3: f32):
    linalg.yield %arg2 : f32
  } -> tensor<3x4xf32>
  %2 = "mhlo.broadcast_in_dim"(%arg1) {broadcast_dimensions = dense<[0, 1]> : tensor<2xi64>} : (tensor<3x1xf32>) -> tensor<3x4xf32>
  %3 = mhlo.complex(%arg0, %2) : (tensor<3x4xf32>, tensor<3x4xf32>) -> tensor<3x4xcomplex<f32>>
  return %3 : tensor<3x4xcomplex<f32>>
}
```

So the error is due to `ElideComplexPattern` just erasing `Complex` without any replacement.

**Comment by alliemartens** [comment]
Hi Jacques, assigning this to you as we have it listed as a P1. Please route to another owner if needed!

**Comment by jpienaar** [comment]
Potential fix sent upstream (there is an alternative locally here, depending on if the upstream change in isolation is fine).

**Comment by jpienaar** [comment]
Changed it to https://github.com/google/iree/pull/9620 which is more local and I think better.

**Comment by rsuderman** [comment]
Correct me if I am wrong: do we actually have a plan for how we return buffers of complex numbers? To my knowledge we don't have a standardized representation of the real+imaginary components (e.g. interleaved) nor the type information appended to the tensor.

In other words, if the return type is a `tensor<*xComplex<f32>>` we don't have a mechanism to generate or describe it as a buffer.

**Comment by jpienaar** [comment]
`./tools/iree-compile --iree-input-type=mhlo /tmp/t1.mlir --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=llvm-cpu` working at head post last change on test case. So
