### ISSUE TITLE
ireec crash for JAX cummax computation

### ISSUE THREAD

**Issue by hawkinsp** [iree-org/iree#9285]
Repro:

```
import iree.compiler

CODE = """
#loc0 = loc(unknown)
module @jit_prim_fun.0 {
  func.func public @main(%arg0: tensor<3x4x5xf32> loc(unknown)) -> tensor<3x4x5xf32> {
    %0 = call @cummax(%arg0) : (tensor<3x4x5xf32>) -> tensor<3x4x5xf32> loc(#loc1)
    return %0 : tensor<3x4x5xf32> loc(#loc0)
  } loc(#loc0)
  func.func private @cummax(%arg0: tensor<3x4x5xf32> loc(unknown)) -> tensor<3x4x5xf32> {
    %0 = "mhlo.reverse"(%arg0) {dimensions = dense<1> : tensor<1xi64>} : (tensor<3x4x5xf32>) -> tensor<3x4x5xf32> loc(#loc2)
    %1 = "mhlo.slice"(%0) {limit_indices = dense<[3, 3, 5]> : tensor<3xi64>, start_indices = dense<0> : tensor<3xi64>, strides = dense<[1, 2, 1]> : tensor<3xi64>} : (tensor<3x4x5xf32>) -> tensor<3x2x5xf32> loc(#loc3)
    %2 = "mhlo.slice"(%0) {limit_indices = dense<[3, 4, 5]> : tensor<3xi64>, start_indices = dense<[0, 1, 0]> : tensor<3xi64>, strides = dense<[1, 2, 1]> : tensor<3xi64>} : (tensor<3x4x5xf32>) -> tensor<3x2x5xf32> loc(#loc4)
    %3 = mhlo.maximum %1, %2 : tensor<3x2x5xf32> loc(#loc5)
    %4 = "mhlo.slice"(%3) {limit_indices = dense<[3, 1, 5]> : tensor<3xi64>, start_indices = dense<0> : tensor<3xi64>, strides = dense<[1, 2, 1]> : tensor<3xi64>} : (tensor<3x2x5xf32>) -> tensor<3x1x5xf32> loc(#loc6)
    %5 = "mhlo.slice"(%3) {limit_indices = dense<[3, 2, 5]> : tensor<3xi64>, start_indices = dense<[0, 1, 0]> : tensor<3xi64>, strides = dense<[1, 2, 1]> : tensor<3xi64>} : (tensor<3x2x5xf32>) -> tensor<3x1x5xf32> loc(#loc7)
    %6 = mhlo.maximum %4, %5 : tensor<3x1x5xf32> loc(#loc5)
    %7 = "mhlo.slice"(%6) {limit_indices = dense<[3, 0, 5]> : tensor<3xi64>, start_indices = dense<0> : tensor<3xi64>, strides = dense<1> : tensor<3xi64>} : (tensor<3x1x5xf32>) -> tensor<3x0x5xf32> loc(#loc8)
    %8 = "mhlo.slice"(%3) {limit_indices = dense<[3, 2, 5]> : tensor<3xi64>, start_indices = dense<[0, 2, 0]> : tensor<3xi64>, strides = dense<[1, 2, 1]> : tensor<3xi64>} : (tensor<3x2x5xf32>) -> tensor<3x0x5xf32> loc(#loc9)
    %9 = mhlo.maximum %7, %8 : tensor<3x0x5xf32> loc(#loc5)
    %10 = "mhlo.slice"(%3) {limit_indices = dense<[3, 1, 5]> : tensor<3xi64>, start_indices = dense<0> : tensor<3xi64>, strides = dense<1> : tensor<3xi64>} : (tensor<3x2x5xf32>) -> tensor<3x1x5xf32> loc(#loc10)
    %11 = "mhlo.concatenate"(%10, %9) {dimension = 1 : i64} : (tensor<3x1x5xf32>, tensor<3x0x5xf32>) -> tensor<3x1x5xf32> loc(#loc11)
    %12 = mhlo.constant dense<0.000000e+00> : tensor<f32> loc(#loc1)
    %13 = "mhlo.pad"(%11, %12) {edge_padding_high = dense<[0, 1, 0]> : tensor<3xi64>, edge_padding_low = dense<0> : tensor<3xi64>, interior_padding = dense<[0, 1, 0]> : tensor<3xi64>} : (tensor<3x1x5xf32>, tensor<f32>) -> tensor<3x2x5xf32> loc(#loc12)
    %14 = mhlo.constant dense<0.000000e+00> : tensor<f32> loc(#loc1)
    %15 = "mhlo.pad"(%6, %14) {edge_padding_high = dense<0> : tensor<3xi64>, edge_padding_low = dense<[0, 1, 0]> : tensor<3xi64>, interior_padding = dense<[0, 1, 0]> : tensor<3xi64>} : (tensor<3x1x5xf32>, tensor<f32>) -> tensor<3x2x5xf32> loc(#loc13)
    %16 = mhlo.add %13, %15 : tensor<3x2x5xf32> loc(#loc14)
    %17 = "mhlo.slice"(%16) {limit_indices = dense<[3, 1, 5]> : tensor<3xi64>, start_indices = dense<0> : tensor<3xi64>, strides = dense<1> : tensor<3xi64>} : (tensor<3x2x5xf32>) -> tensor<3x1x5xf32> loc(#loc10)
    %18 = "mhlo.slice"(%0) {limit_indices = dense<[3, 4, 5]> : tensor<3xi64>, start_indices = dense<[0, 2, 0]> : tensor<3xi64>, strides = dense<[1, 2, 1]> : tensor<3xi64>} : (tensor<3x4x5xf32>) -> tensor<3x1x5xf32> loc(#loc15)
    %19 = mhlo.maximum %17, %18 : tensor<3x1x5xf32> loc(#loc5)
    %20 = "mhlo.slice"(%0) {limit_indices = dense<[3, 1, 5]> : tensor<3xi64>, start_indices = dense<0> : tensor<3xi64>, strides = dense<1> : tensor<3xi64>} : (tensor<3x4x5xf32>) -> tensor<3x1x5xf32> loc(#loc10)
    %21 = "mhlo.concatenate"(%20, %19) {dimension = 1 : i64} : (tensor<3x1x5xf32>, tensor<3x1x5xf32>) -> tensor<3x2x5xf32> loc(#loc11)
    %22 = mhlo.constant dense<0.000000e+00> : tensor<f32> loc(#loc1)
    %23 = "mhlo.pad"(%21, %22) {edge_padding_high = dense<[0, 1, 0]> : tensor<3xi64>, edge_padding_low = dense<0> : tensor<3xi64>, interior_padding = dense<[0, 1, 0]> : tensor<3xi64>} : (tensor<3x2x5xf32>, tensor<f32>) -> tensor<3x4x5xf32> loc(#loc12)
    %24 = mhlo.constant dense<0.000000e+00> : tensor<f32> loc(#loc1)
    %25 = "mhlo.pad"(%16, %24) {edge_padding_high = dense<0> : tensor<3xi64>, edge_padding_low = dense<[0, 1, 0]> : tensor<3xi64>, interior_padding = dense<[0, 1, 0]> : tensor<3xi64>} : (tensor<3x2x5xf32>, tensor<f32>) -> tensor<3x4x5xf32> loc(#loc13)
    %26 = mhlo.add %23, %25 : tensor<3x4x5xf32> loc(#loc14)
    %27 = "mhlo.reverse"(%26) {dimensions = dense<1> : tensor<1xi64>} : (tensor<3x4x5xf32>) -> tensor<3x4x5xf32> loc(#loc2)
    return %27 : tensor<3x4x5xf32> loc(#loc1)
  } loc(#loc1)
} loc(#loc0)
#loc1 = loc("jit(cummax)/jit(main)/cummax[axis=1 reverse=True]"("/Users/phawkins/p/jax/tests/lax_test.py":1972:1))
#loc2 = loc("jit(cummax)/jit(main)/rev[dimensions=(1,)]"("/Users/phawkins/p/jax/tests/lax_test.py":1972:1))
#loc3 = loc("jit(cummax)/jit(main)/slice[start_indices=(0, 0, 0) limit_indices=(3, 3, 5) strides=(1, 2, 1)]"("/Users/phawkins/p/jax/tests/lax_test.py":1972:1))
#loc4 = loc("jit(cummax)/jit(main)/slice[start_indices=(0, 1, 0) limit_indices=(3, 4, 5) strides=(1, 2, 1)]"("/Users/phawkins/p/jax/tests/lax_test.py":1972:1))
#loc5 = loc("jit(cummax)/jit(main)/max"("/Users/phawkins/p/jax/tests/lax_test.py":1972:1))
#loc6 = loc("jit(cummax)/jit(main)/slice[start_indices=(0, 0, 0) limit_indices=(3, 1, 5) strides=(1, 2, 1)]"("/Users/phawkins/p/jax/tests/lax_test.py":1972:1))
#loc7 = loc("jit(cummax)/jit(main)/slice[start_indices=(0, 1, 0) limit_indices=(3, 2, 5) strides=(1, 2, 1)]"("/Users/phawkins/p/jax/tests/lax_test.py":1972:1))
#loc8 = loc("jit(cummax)/jit(main)/slice[start_indices=(0, 0, 0) limit_indices=(3, 0, 5) strides=(1, 1, 1)]"("/Users/phawkins/p/jax/tests/lax_test.py":1972:1))
#loc9 = loc("jit(cummax)/jit(main)/slice[start_indices=(0, 2, 0) limit_indices=(3, 2, 5) strides=(1, 2, 1)]"("/Users/phawkins/p/jax/tests/lax_test.py":1972:1))
#loc10 = loc("jit(cummax)/jit(main)/slice[start_indices=(0, 0, 0) limit_indices=(3, 1, 5) strides=(1, 1, 1)]"("/Users/phawkins/p/jax/tests/lax_test.py":1972:1))
#loc11 = loc("jit(cummax)/jit(main)/concatenate[dimension=1]"("/Users/phawkins/p/jax/tests/lax_test.py":1972:1))
#loc12 = loc("jit(cummax)/jit(main)/pad[padding_config=((0, 0, 0), (0, 1, 1), (0, 0, 0))]"("/Users/phawkins/p/jax/tests/lax_test.py":1972:1))
#loc13 = loc("jit(cummax)/jit(main)/pad[padding_config=((0, 0, 0), (1, 0, 1), (0, 0, 0))]"("/Users/phawkins/p/jax/tests/lax_test.py":1972:1))
#loc14 = loc("jit(cummax)/jit(main)/add"("/Users/phawkins/p/jax/tests/lax_test.py":1972:1))
#loc15 = loc("jit(cummax)/jit(main)/slice[start_indices=(0, 2, 0) limit_indices=(3, 4, 5) strides=(1, 2, 1)]"("/Users/phawkins/p/jax/tests/lax_test.py":1972:1))
"""

iree_binary = iree.compiler.compile_str(
    CODE, target_backends=["dylib"], input_type="mhlo")

```

Output:
```
Traceback (most recent call last):
  File "/Users/phawkins/p/jax/t.py", line 59, in <module>
    iree_binary = iree.compiler.compile_str(
  File "/Users/phawkins/.pyenv/versions/py310/lib/python3.10/site-packages/iree/compiler/tools/core.py", line 293, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/Users/phawkins/.pyenv/versions/py310/lib/python3.10/site-packages/iree/compiler/tools/binaries.py", line 200, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile
Diagnostics:
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  libIREECompilerAggregateCAPI.dylib 0x00000001111b04ac llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  libIREECompilerAggregateCAPI.dylib 0x00000001111af48c llvm::sys::RunSignalHandlers() + 128
2  libIREECompilerAggregateCAPI.dylib 0x00000001111b0b00 llvm::sys::PrintStackTraceOnErrorSignal(llvm::StringRef, bool) + 708
3  libsystem_platform.dylib           0x00000001b06534a4 _sigtramp + 56
4  libIREECompilerAggregateCAPI.dylib 0x0000000111832074 mlir::memref::SubViewOp::getDroppedDims() + 304
5  libIREECompilerAggregateCAPI.dylib 0x0000000111f634cc mlir::createMemRefToLLVMPass() + 57312
6  libIREECompilerAggregateCAPI.dylib 0x0000000111f62cec mlir::createMemRefToLLVMPass() + 55296
7  libIREECompilerAggregateCAPI.dylib 0x00000001148cb5c0 mlir::ConversionPattern::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&) const + 200
8  libIREECompilerAggregateCAPI.dylib 0x00000001148fd47c mlir::PatternApplicator::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&, llvm::function_ref<bool (mlir::Pattern const&)>, llvm::function_ref<void (mlir::Pattern const&)>, llvm::function_ref<mlir::LogicalResult (mlir::Pattern const&)>) + 744
9  libIREECompilerAggregateCAPI.dylib 0x00000001148d56e0 mlir::applyAnalysisConversion(mlir::Operation*, mlir::ConversionTarget&, mlir::FrozenRewritePatternSet const&, llvm::DenseSet<mlir::Operation*, llvm::DenseMapInfo<mlir::Operation*, void>>&, llvm::function_ref<void (mlir::Diagnostic&)>) + 15692
10 libIREECompilerAggregateCAPI.dylib 0x00000001148cf058 mlir::applyPartialConversion(llvm::ArrayRef<mlir::Operation*>, mlir::ConversionTarget&, mlir::FrozenRewritePatternSet const&, llvm::DenseSet<mlir::Operation*, llvm::DenseMapInfo<mlir::Operation*, void>>*) + 4236
11 libIREECompilerAggregateCAPI.dylib 0x00000001148d1748 mlir::applyPartialConversion(mlir::Operation*, mlir::ConversionTarget&, mlir::FrozenRewritePatternSet const&, llvm::DenseSet<mlir::Operation*, llvm::DenseMapInfo<mlir::Operation*, void>>*) + 76
12 libIREECompilerAggregateCAPI.dylib 0x00000001128b43a4 spirv_cross::DominatorBuilder::lift_continue_block_dominator() + 1553188
13 libIREECompilerAggregateCAPI.dylib 0x00000001111e2384 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) + 724
14 libIREECompilerAggregateCAPI.dylib 0x00000001111e2c3c mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) + 348
15 libIREECompilerAggregateCAPI.dylib 0x00000001111e6cf0 mlir::PassInstrumentor::runAfterAnalysis(llvm::StringRef, mlir::TypeID, mlir::Operation*) + 7112
16 libIREECompilerAggregateCAPI.dylib 0x00000001111e3ab8 mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool) + 1232
17 libIREECompilerAggregateCAPI.dylib 0x00000001111e23b4 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) + 772
18 libIREECompilerAggregateCAPI.dylib 0x00000001111e2c3c mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) + 348
19 libIREECompilerAggregateCAPI.dylib 0x00000001111e61f8 mlir::PassInstrumentor::runAfterAnalysis(llvm::StringRef, mlir::TypeID, mlir::Operation*) + 4304
20 libIREECompilerAggregateCAPI.dylib 0x000000011275cc08 spirv_cross::DominatorBuilder::lift_continue_block_dominator() + 146312
21 libIREECompilerAggregateCAPI.dylib 0x00000001111e2384 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) + 724
22 libIREECompilerAggregateCAPI.dylib 0x00000001111e2c3c mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) + 348
23 libIREECompilerAggregateCAPI.dylib 0x00000001111e6cf0 mlir::PassInstrumentor::runAfterAnalysis(llvm::StringRef, mlir::TypeID, mlir::Operation*) + 7112
24 libIREECompilerAggregateCAPI.dylib 0x00000001111e3ab8 mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool) + 1232
25 libIREECompilerAggregateCAPI.dylib 0x00000001111e23b4 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) + 772
26 libIREECompilerAggregateCAPI.dylib 0x00000001111e2c3c mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) + 348
27 libIREECompilerAggregateCAPI.dylib 0x00000001111e61f8 mlir::PassInstrumentor::runAfterAnalysis(llvm::StringRef, mlir::TypeID, mlir::Operation*) + 4304
28 libIREECompilerAggregateCAPI.dylib 0x000000011275d8a0 spirv_cross::DominatorBuilder::lift_continue_block_dominator() + 149536
29 libIREECompilerAggregateCAPI.dylib 0x00000001111e2384 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) + 724
30 libIREECompilerAggregateCAPI.dylib 0x00000001111e2c3c mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) + 348
31 libIREECompilerAggregateCAPI.dylib 0x00000001111e7ef0 mlir::PassInstrumentor::runAfterAnalysis(llvm::StringRef, mlir::TypeID, mlir::Operation*) + 11720
32 libIREECompilerAggregateCAPI.dylib 0x00000001111e7780 mlir::PassInstrumentor::runAfterAnalysis(llvm::StringRef, mlir::TypeID, mlir::Operation*) + 9816
33 libIREECompilerAggregateCAPI.dylib 0x0000000111159518 llvm::ThreadPool::processTasks(llvm::ThreadPoolTaskGroup*) + 916
34 libIREECompilerAggregateCAPI.dylib 0x0000000111159e60 llvm::ThreadPool::~ThreadPool() + 388
35 libsystem_pthread.dylib            0x00000001b063c26c _pthread_start + 148
36 libsystem_pthread.dylib            0x00000001b063708c thread_start + 8


Invoked with:
 iree-compile /Users/phawkins/.pyenv/versions/py310/lib/python3.10/site-packages/iree/compiler/tools/../_mlir_libs/iree-compile - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/Users/phawkins/.pyenv/versions/py310/lib/python3.10/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false

Need more information? Set IREE_SAVE_TEMPS=/some/dir in your environment to save all artifacts and reproducers.
```

**Comment by MaheshRavishankar** [comment]
It is a bug upstream, I'll look into that.

But the configuration chosen here is strange 
```
func.func @_main_dispatch_6() {
  %c1 = arith.constant 1 : index
  %c3 = arith.constant 3 : index
  %c5 = arith.constant 5 : index
  %c0 = arith.constant 0 : index
  %c384 = arith.constant 384 : index
  %c256 = arith.constant 256 : index
  %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) offset(%c256) alignment(64) : !flow.dispatch.tensor<readonly:3x2x5xf32>
  %1 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) offset(%c0) alignment(64) : !flow.dispatch.tensor<readonly:3x4x5xf32>
  %2 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) offset(%c384) alignment(64) : !flow.dispatch.tensor<writeonly:3x5xf32>
  %workgroup_id_x = hal.interface.workgroup.id[0] : index
  %workgroup_count_x = hal.interface.workgroup.count[0] : index
  %workgroup_id_y = hal.interface.workgroup.id[1] : index
  %workgroup_count_y = hal.interface.workgroup.count[1] : index
  scf.for %arg0 = %workgroup_id_y to %c3 step %workgroup_count_y {
    scf.for %arg1 = %workgroup_id_x to %c5 step %workgroup_count_x {
      %3 = flow.dispatch.tensor.load %0, offsets = [%arg0, 0, %arg1], sizes = [1, 1, 1], strides = [%c1, 1, %c1] : !flow.dispatch.tensor<readonly:3x2x5xf32> -> tensor<1x1xf32>
      %4 = flow.dispatch.tensor.load %1, offsets = [%arg0, 2, %arg1], sizes = [1, 1, 1], strides = [%c1, 2, %c1] : !flow.dispatch.tensor<readonly:3x4x5xf32> -> tensor<1x1xf32>
      %5 = linalg.init_tensor [1, 1] : tensor<1x1xf32>
      %6 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%3, %4 : tensor<1x1xf32>, tensor<1x1xf32>) outs(%5 : tensor<1x1xf32>) attrs =  {lowering_config = #iree_codegen.lowering_config<tile_sizes = [[1, 1], [1, 1], [0, 0]]>\
} {
      ^bb0(%arg2: f32, %arg3: f32, %arg4: f32):
        %7 = arith.maxf %arg2, %arg3 : f32
        linalg.yield %7 : f32
      } -> tensor<1x1xf32>
      flow.dispatch.tensor.store %6, %2, offsets = [%arg0, %arg1], sizes = [1, 1], strides = [%c1, %c1] : tensor<1x1xf32> -> !flow.dispatch.tensor<writeonly:3x5xf32>
    }
  }
  return
}
```

@hanhanW I'd expect this to just run on a single thread, i.e not use the tile size of {1, 1}. Maybe this is going down some corner case in the config selection.

**Comment by hanhanW** [comment]
The shape is 3x5. We try to balance the work equally which leads to {1,1} or maybe {1, 2}. We might want to make it run on a single thread if they are small sizes.

**Comment by jpienaar** [comment]
This looks similar to bug that was fixed by Matthias (and that got integrated as part of last integrate)

**Comment by hanhanW** [comment]
verified that it's fixed.
