### ISSUE TITLE
Lowering failure for mhlo.dynamic-update-slice with empty update

### ISSUE THREAD

**Issue by hawkinsp** [iree-org/iree#9293]
Repro:
```
import iree.compiler

CODE = """
#loc0 = loc(unknown)
module @jit_prim_fun.0 {
  func.func public @main(%arg0: tensor<7x5x3xi32> loc(unknown), %arg1: tensor<2x0x1xi32> loc(unknown), %arg2: tensor<i32> loc(unknown), %arg3: tensor<i32> loc(unknown), %arg4: tensor<i32> loc(unknown)) -> tensor<7x5x3xi32> {
    %0 = "mhlo.dynamic-update-slice"(%arg0, %arg1, %arg2, %arg3, %arg4) : (tensor<7x5x3xi32>, tensor<2x0x1xi32>, tensor<i32>, tensor<i32>, tensor<i32>) -> tensor<7x5x3xi32> loc(#loc1)
    return %0 : tensor<7x5x3xi32> loc(#loc0)
  } loc(#loc0)
} loc(#loc0)
#loc1 = loc("jit(dynamic_update_slice)/jit(main)/dynamic_update_slice"("/Users/phawkins/p/jax/tests/lax_test.py":1627:1))
"""

iree_binary = iree.compiler.compile_str(
    CODE, target_backends=["dylib"], input_type="mhlo")
```

Output:
```
Traceback (most recent call last):
  File "/Users/phawkins/p/jax/t.py", line 14, in <module>
    iree_binary = iree.compiler.compile_str(
  File "/Users/phawkins/.pyenv/versions/py310/lib/python3.10/site-packages/iree/compiler/tools/core.py", line 293, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/Users/phawkins/.pyenv/versions/py310/lib/python3.10/site-packages/iree/compiler/tools/binaries.py", line 200, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile
Diagnostics:
/Users/phawkins/p/jax/tests/lax_test.py:1627:1: error: expected result type to be 'memref<2x0xi32, affine_map<(d0, d1) -> (0)>>' or a rank-reduced version. (mismatch of result layout)
    def args_maker():
^
/Users/phawkins/p/jax/tests/lax_test.py:1627:1: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"llvm", "embedded-elf-x86_64", {cpu_features = "", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128", native_vector_size = 16 : index, target_triple = "x86_64-unknown-unknown-eabi-elf"}>
    def args_maker():
^
/Users/phawkins/p/jax/tests/lax_test.py:1627:1: error: failed to serialize executables
    def args_maker():
^
compilation failed


Invoked with:
 iree-compile /Users/phawkins/.pyenv/versions/py310/lib/python3.10/site-packages/iree/compiler/tools/../_mlir_libs/iree-compile - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/Users/phawkins/.pyenv/versions/py310/lib/python3.10/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
```

**Comment by MaheshRavishankar** [comment]
This has a tensor<0x2xi16> . THis is invalid shape. I dont think we support such cases. Might be Python -> MHLO conversion error?

**Comment by sdasgup3** [comment]
From MHLO's point of view. having zero as dimension sizes is  OK and the behavior of ops consuming them is also defined.

**Comment by MaheshRavishankar** [comment]
More discussion on this in #9297

**Comment by rsuderman** [comment]
A decent number of these should just have reasonable canonicalizers. Overall its kinda silly to have a 0-length update as it is effectively a no-op and should be converted like one.

**Comment by rsuderman** [comment]
Fixed upstream in https://github.com/tensorflow/mlir-hlo/commit/79ca99e186d6c58ea80fb639a6a3044c7658af73
