### ISSUE TITLE
Missing legalization for variadic mhlo.reduce_window 

### ISSUE THREAD

**Issue by hawkinsp** [iree-org/iree#9298]
```
import iree.compiler

CODE = """
#loc0 = loc(unknown)
module @jit_prim_fun.0 {
  func.func public @main(%arg0: tensor<3x2x4x6xf32> loc(unknown), %arg1: tensor<3x2x4x6xf32> loc(unknown), %arg2: tensor<f32> loc(unknown), %arg3: tensor<f32> loc(unknown)) -> (tensor<5x2x7x13xf32>, tensor<5x2x7x13xf32>) {
    %0:2 = "mhlo.reduce_window"(%arg0, %arg1, %arg2, %arg3) ({
    ^bb0(%arg4: tensor<f32> loc(unknown), %arg5: tensor<f32> loc(unknown), %arg6: tensor<f32> loc(unknown), %arg7: tensor<f32> loc(unknown)):
      %1 = mhlo.add %arg4, %arg6 : tensor<f32> loc(#loc2)
      %2 = mhlo.maximum %arg5, %arg7 : tensor<f32> loc(#loc3)
      "mhlo.return"(%1, %2) : (tensor<f32>, tensor<f32>) -> () loc(#loc1)
    }) {base_dilations = dense<[2, 1, 3, 2]> : tensor<4xi64>, padding = dense<[[0, 1], [1, 0], [2, 3], [0, 2]]> : tensor<4x2xi64>, window_dilations = dense<[1, 2, 2, 1]> : tensor<4xi64>, window_dimensions = dense<[2, 1, 2, 1]> : tensor<4xi64>, window_strides = dense<[1, 2, 2, 1]> : tensor<4xi64>} : (tensor<3x2x4x6xf32>, tensor<3x2x4x6xf32>, tensor<f32>, tensor<f32>) -> (tensor<5x2x7x13xf32>, tensor<5x2x7x13xf32>) loc(#loc1)
    return %0#0, %0#1 : tensor<5x2x7x13xf32>, tensor<5x2x7x13xf32> loc(#loc0)
  } loc(#loc0)
} loc(#loc0)
#loc1 = loc("jit(reduce_window)/jit(main)/reduce_window[consts=() window_dimensions=(2, 1, 2, 1) window_strides=(1, 2, 2, 1) padding=((0, 1), (1, 0), (2, 3), (0, 2)) base_dilation=(2, 1, 3, 2) window_dilation=(1, 2, 2, 1)]"("/Users/phawkins/p/jax/tests/lax_test.py":1875:1))
#loc2 = loc("jit(reduce_window)/jit(main)/add"("/Users/phawkins/p/jax/tests/lax_test.py":1871:1))
#loc3 = loc("jit(reduce_window)/jit(main)/max"("/Users/phawkins/p/jax/tests/lax_test.py":1871:1))
"""

iree_binary = iree.compiler.compile_str(
    CODE, target_backends=["dylib"], input_type="mhlo")
```

```
Traceback (most recent call last):
  File "/Users/phawkins/p/jax/t.py", line 21, in <module>
    iree_binary = iree.compiler.compile_str(
  File "/Users/phawkins/.pyenv/versions/py310/lib/python3.10/site-packages/iree/compiler/tools/core.py", line 293, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/Users/phawkins/.pyenv/versions/py310/lib/python3.10/site-packages/iree/compiler/tools/binaries.py", line 200, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile
Diagnostics:
/Users/phawkins/p/jax/tests/lax_test.py:1875:1: error: failed to legalize operation 'mhlo.reduce_window' that was explicitly marked illegal
      return lax.reduce_window(operands, init_values, reducer, dims, strides,
^
compilation failed


Invoked with:
 iree-compile /Users/phawkins/.pyenv/versions/py310/lib/python3.10/site-packages/iree/compiler/tools/../_mlir_libs/iree-compile - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/Users/phawkins/.pyenv/versions/py310/lib/python3.10/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
```

**Comment by rsuderman** [comment]
Just verified to be working at head.
