### ISSUE TITLE
Crash unmarshalling an i32 from a custom module call

### ISSUE THREAD

**Issue by stellaraccident** [iree-org/iree#9967]
### Issue body

Getting a segmentation fault at bytecode_dispatch.c:515.

I imagine a simpler example could be made, but this comes from some hacking I was doing to test out Python custom modules. Repro here: https://gist.github.com/stellaraccident/7d7ddae182ddc235dc4ffaf60aee284e

Just compile the MLIR file and run the python file (after `source .env && export PYTHONPATH` from your build dir).

**Comment by stellaraccident** [comment]
If I change the signature to return void, then it gets a bit further but still segfaults:

```
    #0 0x7f65b009b7c6 in iree_vm_bytecode_external_leave /usr/local/google/home/laurenzo/src/iree/runtime/src/iree/vm/bytecode_dispatch.c:257:9
    #1 0x7f65b009b7c6 in iree_vm_bytecode_dispatch /usr/local/google/home/laurenzo/src/iree/runtime/src/iree/vm/bytecode_dispatch.c:1743:5
```

It is ASAN clean up to that point. It may be something not good being done in the new Python logic, but if it is, it must be stomping valid memory.
